### ISSUE TITLE
Failed payload & Unmarshalling

### ISSUE THREAD

**Issue by paralovosca** [davidnewhall/unifi-poller#100]
Uploading log with sample failed payloads and unmarshalling events.

[log.txt](https://github.com/davidnewhall/unifi-poller/files/3511290/log.txt)

Unifi Controller: 5.11.39
Hosted on Mac OSX 10.13.6

**Comment by davidnewhall** [comment]
Seems related to #97. Will investigate. Thanks!!

**Comment by davidnewhall** [comment]
I believe this is fixed in master. It won't make it into home-brew until I cut a release. Until then, you can attempt to build it yourself; pretty easy on a Mac.
