### ISSUE TITLE
Feature Request: USG (Pro) Temperature

### ISSUE THREAD

**Issue by ChristophGoth** [davidnewhall/unifi-poller#106]
Just looked around to add some USG Environment Stats (Fan,  Temperature) to the dashboard but cant find them in the database. Controller gives them in GUI so i think they should be available in the API (4 times temperature).

Same for Lan2 traffic stats @USG-Pro

If you tell me what kind of logs u need i can provide them to you.

**Comment by davidnewhall** [comment]
Were you able to find any temperature readings in the API output? I've been unable to figure it out..
