### ISSUE TITLE
Feature Request: Unifi Dream Machine Support

### ISSUE THREAD

**Issue by SasquatchSecurity** [davidnewhall/unifi-poller#107]
Ubiquiti's upcoming UniFi Dream Machine and Dream Machine Pro combine features of a USG and a switch, among other things. Controller 5.11.x supports this and it appears unifi-poller is grabbing data, but it doesn't appear to make it to a table in InfluxDB. unifi-poller -j devices output to a json includes data collected from the UDMP. I can provide example JSONs, if required.

**Comment by davidnewhall** [comment]
I uploaded a test `deb` that should provide this support into the #unifi-poller channel on the Ubiquti Discord. Waiting for some feedback before marking this resolved and cutting a release.
