### ISSUE TITLE
unifi-poller keeps stopping

### ISSUE THREAD

**Issue by Waffull** [davidnewhall/unifi-poller#108]
I don't check the stats but every couple of days.  For as far back as I can remember, most of the times I login to grafana (localip:3000) it shows no data.  If I login to ssh and run:
sudo systemctl restart unifi-poller
the data starts populating again.

Anyway, to force unifi-poller to restart when it stops?

**Comment by davidnewhall** [comment]
This feels similar to #93. Is the poller still running when this happens? If you tail the log file, do you see data? errors? The journald log may help, systemd should restart it if it fails. The logs will hopeful shed some light on this if you can paste some of them.

**Comment by sgroom-lb** [comment]
I just upgraded my unifi controller to 5.11.39
Noticed no stats. Checked the unifi-poller service, stopped. 
Restarted and stats are collecting again. 
Will monitor and advise.

**Comment by davidnewhall** [comment]
Please provide logs form the poller when this happens.

**Comment by sgroom-lb** [comment]
Had a few mins to dig around in the logs around the time I upgraded the controller.
grep'd logs for that timeframe...  https://pastebin.com/NJeNN8A6

**Comment by davidnewhall** [comment]
Sweet thanks! This will be fixed in the next release!

**Comment by sgroom-lb** [comment]
My pleasure!
