### ISSUE TITLE
Docs/Feature Req: Updating w/ install.sh broken

### ISSUE THREAD

**Issue by sgroom-lb** [davidnewhall/unifi-poller#111]
With as well as your install.sh works, can you add a switch to perform an upgrade?
I took a peek at that script and you're way beyond my bash scripting skills. 
lol

**Comment by davidnewhall** [comment]
I can look into that, definitely. For now, run the script without `sudo` and it downloads the latest version. You can then use `rpm -U` or `dpkg -i` to install the downloaded file.

**Comment by davidnewhall** [comment]
What happens when you run the script without sudo now? Did you get an error that the package is already installed? Can you share the error?

**Comment by davidnewhall** [comment]
got this from someone else:
```
curl https://raw.githubusercontent.com/davidnewhall/unifi-poller/master/scripts/install.sh | sudo bash) and got  the error:
[11:59 AM] PianSom: *** up.conf (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package unifi-poller (--install):
 end of file on stdin at conffile prompt
Processing triggers for man-db (2.8.5-2) ...
Errors were encountered while processing:
 unifi-poller
```

It appears to have a problem when trying to replace the config file and stdin is caught by the script. I'll see if I can fix this...
