### ISSUE TITLE
Monthly WAN client usage

### ISSUE THREAD

**Issue by ntalekt** [davidnewhall/unifi-poller#112]
I stumbled upon your glorious project while looking for a solution. Is it possible to isolate WAN usage by client over a month time period? My use-case is that my ISP caps data usage to 1TB/month and i'd like to understand which client is using the majority.

As a side note, thank you for the wonderful documentation. I was able to spin up Grafana/Influx easily along with the unifi-poller via Docker. Appreciate it.

**Comment by davidnewhall** [comment]
The answer to your question is "yes" but the Graph's I've provided probably wont let you drill into that level of detail: I've never tried. The poller is copying all the data for each client into influxdb, so you can certainly create graphs in Grafana that display the data use of a client over a period of time. 

I'm not very well equipped to provide support for creating custom graphs; Grafana is all about trial and error. Start by copying one of the graphs I've created into a new dashboard. Change metrics until you get to the data you're looking for.

Note: I don't think the unifi controller can or will distinguish between local and wan traffic: it's all the same in the client metrics.

We have a Discord channel you can jump into; there might be some others there that have done this and could provide better assistance. https://discord.gg/DyVsMyt

**Comment by ntalekt** [comment]
Thanks for the response. I'll take my question to discord.

**Comment by davidnewhall** [comment]
Re-opening to keep exposure on your question. Someone may see this and have an answer. 🤞

**Comment by davidnewhall** [comment]
I've recently gone through all the data on the controller, again. What you seek is not there. There is no way to discern Internet traffic from LAN traffic at the client level. Maybe ask Ubiquiti to add this data set? Good luck!
