### ISSUE TITLE
uap dashboard not showing some data, uap measurement missing in db

### ISSUE THREAD

**Issue by boelters** [davidnewhall/unifi-poller#118]
Hello!  

Excited to get this project running for a few small businesses i support, but i appear to be getting stuck getting uap data into the system.  I've followed this install doc (i believe) completely and done a bit of troubleshooting (albeit not much).  Here's what my uap dashboard renders:

![image](https://user-images.githubusercontent.com/55367158/64929686-b461b000-d7ee-11e9-8c5d-390937dd90ef.png)

This is what my database looks like:

`Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 1.1.1
InfluxDB shell version: 1.1.1
> use unifi
Using database unifi
> show databases
name: databases
name

_internal
unifi

> show measurements
name: measurements
name

clients
subsystems
usw
usw_ports

`

And this is what my debug log shows (sanitized, hopefully):
[https://pastebin.com/DizGiTsC](https://pastebin.com/DizGiTsC)

The last line here shows 0 APs, which is incorrect as we have 8 of them.  

I've attempted to reinstall unifi-poller assuming it'd attempt to create the database structure again, but obviously that didn't work.

Any help would be much appreciated!

**Comment by davidnewhall** [comment]
Thanks for the report! You're hitting a bug. This is the unfortunate side effect of working with the UniFi API - some things change from time to time and break the poller. I'll get a fix for this out in the next day or two.
```
Sep 15 19:08:53 grafana unifi-poller[1938]: 2019/09/15 19:08:53.274548 devices.go:76: [ERROR] json.Unmarshal(uap): json: cannot unmarshal number into Go struct field .ht of type string
```

**Comment by davidnewhall** [comment]
Are you running poller from a package? deb or rpm? I may be able to provide a test package; let me know! 

Another thought: Your influxdb version appears old and may cause some other odd quirks. Recommend upgrading that if you can.

**Comment by boelters** [comment]
yep, poller came from a deb.  I updated my influxdb to 1.7.8-1 -- appears to have the same issue ( same error in debug )

**Comment by davidnewhall** [comment]
Give this a try. Run `dpkg -i unifi-poller_1.5.3-422_amd64.deb` to install it. Should restart automatically, but you can always use `systemctl` to restart it if the package doesn't do it. Not much else to it, the data should begin reporting immediately. If you get another error, please post it. Thanks!

[Uploading unifi-p oller_1.5.3-422_amd64.deb.gz…]()

**Comment by boelters** [comment]
That did it! Thanks for the quick turnaround and assistance!
