### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by swedishstyle** [davidnewhall/unifi-poller#119]
When starting unifi-poller, I'm getting the following authentication failure when trying to authenticate against my Unifi controller:

Sept 19 09:44:16 webserver unifi-poller [3731]: 2019/09/19 09:44:16 380093 unifi.go:107: [DEBUG] Downloading https://192.168.1.4:8443/api/login (params: true, error: false)

Sept 19 09:44:17 webserver unifi-poller [3731]: 2019/09/19 09:44:17 380093 main.go:12: [ERROR] unifi controller: authentication failed (user: influx): https://192.168.1.4:8443/api/login (status: 400)

Happy to provide any further details you need. User is definitely created in the Unifi controller and is a read-only admin. Hitting that URL manually in a browser results in the attached screenshot.
![Capture](https://user-images.githubusercontent.com/32089115/65195564-18bc9200-dac3-11e9-89f6-abe1e00523c1.PNG)

**Comment by davidnewhall** [comment]
Can you login to the controller UI with that user/pass? What controller version?

**Comment by davidnewhall** [comment]
Someone posted this in Discord a moment ago...
```
lyzerak: @Scyto boom, its working now on my Synology. The problem was with the password defined in the controller for the user "influx". Firstly I had some "_ and /" in the PW. This didnt work and I receive 400 error while starting up the unifi-poller container. Then Ive changed the PW with regular letters and numbers upper and lower case and it works perfectly fine now. Thanks a lot!
```

**Comment by swedishstyle** [comment]
Wow, thanks for the quick response!

Yep, logging into the controller works with that account just fine.

The password does have some special characters, but not any / or _

I'll try removing special characters and try again for now.

**Comment by swedishstyle** [comment]
Nope, I've left it as only upper/lower case alphanumeric characters, still getting the same 400 error. 

Controller version is 5.11.46

**Comment by davidnewhall** [comment]
These leaves me a bit stumped. Try running a debug command like 
```shell
unifi-poller -c /path/to/up.conf -j d
```
I imagine this will produce a similar error, but maybe something else will come of it.

There is currently no way to make the poller dump the login failure response (other than the `400` code it show you - there is a web page it's not showing you). I'll have to add logic to pass that back through to troubleshoot further. That extra data may or may not be helpful, but I can work on it.

For now, try things like: make a new user with a simple username and password. Iterate on it a bit, and see if you can narrow down some pattern..

**Comment by scyto** [comment]
Also try a short password, say 10 chars or less.
Mine in format of My9password!

**Comment by swedishstyle** [comment]
Soooo it seems I'm just an idiot :)

The special characters may not have been helping, but it also helps when I specify the correct username as well...

I had changed the username while I was testing things, and updated the password in the config file, but not the username itself!

Its working just fine now with a fairly complex ~16 char password, no special characters. I'll play with adding some in later, but for now it's working so I'll leave it alone!

Thanks for your help, enjoy dinner :)
