### ISSUE TITLE
Using a self-signed certificate on the InfluxDB HTTP endpoint makes Unifi-Poller fail.

### ISSUE THREAD

**Issue by dpaeme** [davidnewhall/unifi-poller#120]
How to reproduce:
1/ Set up InfluxDB with a self-signed certificate on the HTTP endpoint
2/ Point Unifi-Poller in it's direction
3/ See Unifi-Poller fail to connect with 

"Sep 20 15:02:55 zabbix unifi-poller[20425]: 2019/09/20 15:02:55 [ERROR] (1/0) reporting metrics: influxdb.Write(points): Post https://172.27.0.26:8086/write?consistency=&db=unifi&precision=ns&rp=: x509: certificate signed by unknown authority
" - or other funky errors.

Would there be a way to disable SSL certificate checking?

**Comment by davidnewhall** [comment]
Set `verify_ssl` to false.
https://github.com/davidnewhall/unifi-poller/blob/master/examples/up.conf.example#L64-L67

**Comment by davidnewhall** [comment]
Can you elaborate on this statement:
> or other funky errors.

**Comment by dpaeme** [comment]
> Can you elaborate on this statement:
> 
> > or other funky errors.

Other types of SSL errors, eg: I started out with a certificate without CN or SANs and got another one.

**Comment by dpaeme** [comment]
> Set `verify_ssl` to false.
> https://github.com/davidnewhall/unifi-poller/blob/master/examples/up.conf.example#L64-L67

Is set to false, but only seems to be valid for the connections to the Unifi Controller, not for the http connection to Influx

**Comment by davidnewhall** [comment]
That is correct, it does not control influx. There is no way to turn that off. Recommend using Lets encrypt or something to get a free cert.

**Comment by davidnewhall** [comment]
I have a test package to try that provides a new config option to ignore the SSL cert on influx. Are you using deb or rpm? docker maybe? Lemme know which.. Thanks!

**Comment by dpaeme** [comment]
> I have a test package to try that provides a new config option to ignore the SSL cert on influx. Are you using deb or rpm? docker maybe? Lemme know which.. Thanks!

A .deb would be nice, I'm running Debian 10.

**Comment by davidnewhall** [comment]
Give this a whirl. 
[unifi-poller_1.5.3-424_amd64.deb.gz](https://github.com/davidnewhall/unifi-poller/files/3638399/unifi-poller_1.5.3-424_amd64.deb.gz)

The config file has a new option available. See example here: https://github.com/davidnewhall/unifi-poller/blob/dn2_fixes/examples/up.conf.example#L46-L47

**Comment by dpaeme** [comment]
Nice, looks like it works perfectly! Data is flowing from the Unifi setup into Influx.

Impressive support, David, it's greatly appreciated!

**Comment by davidnewhall** [comment]
Thank you for testing! I'll release an updated version with this fix soon. For now the deb you're running is the latest code. Hope the poller proves useful! Good luck!
