### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by MrMoosieMan** [davidnewhall/unifi-poller#122]
I'm new to all this.  I'm running everything with unRAID as Docker containers.  I am unable to see any data within Grafana.  Any help is greatly appreciated.

- I have Influx setup and a database created using the below settings.  One thing I was unsure about was should I be using "localhost" or the IP of Grafana or the Unifi-Poller

influx -host localhost -port 8086
CREATE DATABASE unifi
CREATE USER unifi WITH PASSWORD 'unifi' WITH ALL PRIVILEGES
GRANT ALL ON unifi TO unifiConnected to http://localhost:8086 version 1.7.8
InfluxDB shell version: 1.7.8
CREATE DATABASE unifi
CREATE USER unifi WITH PASSWORD 'unifi' WITH ALL PRIVILEGES
GRANT ALL ON unifi TO unifi

- I have Grafana pointed to the Influx database and I get "success" when I test the connection.

- I attached my UniFi-Poller config. [UniFi-Poller config.pdf](https://github.com/davidnewhall/unifi-poller/files/3647941/UniFi-Poller.config.pdf)

**Comment by MrMoosieMan** [comment]
I figured out the issue.  Turns out my routing was messed up with the UniFi-Poller.  Corrected that issue and presto-magic its working.  Thank you for all the hard work.  :)

**Comment by davidnewhall** [comment]
Yay! Glad you got it rolling!
