### ISSUE TITLE
Client Insights - No Switch/Camera Bandwidth

### ISSUE THREAD

**Issue by ataylor1988** [davidnewhall/unifi-poller#125]
So I am new to the world of grafana/unifi-poller/influx, but with the Client Insights dashboard I am not getting any switch bandwidth, but if i look at the USW insights for the same site I am getting the information.

I am sure this is a simple fix I can do, but the query in grafana seems to be correct.

**Comment by davidnewhall** [comment]
I take it you figured it out? 🍰

**Comment by ataylor1988** [comment]
Yea,

It was just me being dumb.  Thought I should be see switch throughput and camera throughput, which I do not have any unifi camera’s so I was just miss reading the dashboard.
