### ISSUE TITLE
Switch data not showing

### ISSUE THREAD

**Issue by Jeroen973** [davidnewhall/unifi-poller#128]
Hi there,

I just installed the latest verssion of the poller and dashboards on my CentOS system. Everything workes fine and look sgreat so thanks for that. 
I have an issue where the poller thinks I do not have a switch in my network. I do have one but it is not shwoing up. if I check my logs is see the following lines:

Oct  2 16:11:46 hades chronograf: time="2019-10-02T16:11:46+02:00" level=info msg="Response: OK" component=server method=GET remote_addr="185.46.213.75:19753" response_time="40.117µs" status=200 Oct  2 16:11:50 hades unifi-poller: 2019/10/02 16:11:50 [ERROR] json.Unmarshal(usw): json: cannot unmarshal number into Go struct field USW.stp_priority of type string Oct  2 16:11:50 hades unifi-poller: 2019/10/02 16:11:50 [ERROR] Enable Debug Logging to output the failed payload.
Oct  2 16:11:50 hades influxd: [httpd] 127.0.0.1 - unifi [02/Oct/2019:16:11:50 +0200] "POST /write?consistency=&db=unifi&precision=ns&rp= HTTP/1.1" 204 0 "-" "InfluxDBClient" 94061732-e51e-11e9-a98c-cad656d28ad9 21338 Oct  2 16:11:50 hades unifi-poller: 2019/10/02 16:11:50 [INFO] UniFi Measurements Recorded. Sites: 1, Clients: 37, Wireless APs: 12, Gateways: 0, Switches: 0, Points: 134, Fields: 7017 Oct  2 16:11:57 hades chronograf: time="2019-10-02T16:11:57+02:00" level=info msg="Response: OK" component=server method=GET remote_addr="185.46.213.75:19753" response_time="18.392µs" status=200 Oct  2 16:12:08 hades chronograf: time="2019-10-02T16:12:08+02:00" level=info msg="Response: OK" component=server method=GET remote_addr="185.46.213.75:19753" response_time="33.485µs" status=200

Can you hepl me with this issue?

Thanks,

Jeroen

**Comment by davidnewhall** [comment]
Hello and thank you for your report! This same problem was reported and corrected #117. Please try the attached package - it contains all the current patches.

[unifi-poller-1.5.3-433.x86_64.rpm.gz](https://github.com/davidnewhall/unifi-poller/files/3682110/unifi-poller-1.5.3-433.x86_64.rpm.gz)

**Comment by Jeroen973** [comment]
Hi David,

Thanks for the quick reply. I missed that one. I did not link it to my issue. Package installed and all working fine now.

Many thanks,

Jeroen
