### ISSUE TITLE
Docker container failing to verify InfluxDB certificate

### ISSUE THREAD

**Issue by Luzifer** [davidnewhall/unifi-poller#129]
As of being a scratch container without any root certificates embedded it's not possible to verify the TLS certificate of the InfluxDB URL when using HTTPs.

A workaround for this issue is to mount the host certificates into the container while IMHO a proper solution would be to ship distro-certificates inside the container.

Workaround:
```bash
# Generic (Debian/Ubuntu/Gentoo/Alpine/...)
docker run \
	... \
	-v /etc/ssl:/etc/ssl:ro \
	... \
	golift/unifi-poller:stable

# Archlinux
docker run \
	... \
	-v /etc/ssl:/etc/ssl:ro \
	-v /etc/ca-certificates:/etc/ca-certificates:ro \
	... \
	golift/unifi-poller:stable
```

As an example how to fix this directly you could add another build step:

```Dockerfile
FROM [...]
[...]

FROM alpine:latest AS certs

FROM scratch
[...]
COPY --from=certs /etc/ssl /etc/ssl
[...]
```

**Comment by davidnewhall** [comment]
Thanks for the report! I'll update [application-builder](https://github.com/golift/application-builder) and port the changes to the Poller as soon as I'm able to!

**Comment by davidnewhall** [comment]
I tried something a little different. Can you test the `ssl_certs` tag?

`docker pull golift/unifi-poller:ssl_certs`

Thank you!!

**Comment by Luzifer** [comment]
That of course works too! :+1:
