### ISSUE TITLE
Error against 5.11.46

### ISSUE THREAD

**Issue by enetics-brian** [davidnewhall/unifi-poller#130]
I'm getting: 
[ERROR] json.Unmarshal(uap): json: cannot unmarshal number into Go struct field .ht of type string 

from a newly installed instance of unifi-poller. I installed via the provided install script:
UniFi Poller v1.5.3-418
UniFi Controller version: 5.11.46

It seems to be able to enumerate clients and sites, but not APs based on the logs.

**Comment by davidnewhall** [comment]
Are you using a deb or rpm or Docker?

**Comment by davidnewhall** [comment]
This is a duplicate of #118. If you let me know how you installed I can give you a package to use until a new version come out with the fix.

**Comment by enetics-brian** [comment]
I installed via the install.sh script in your repo. Running ubuntu, so deb. Thank you very much! This thing is amazing and made my life 100x easier.

**Comment by davidnewhall** [comment]
Try that deb linked at the bottom of #118.

**Comment by enetics-brian** [comment]
That did the trick, thank you!

**Comment by davidnewhall** [comment]
Sweet! I'll have an official release out with all the latest patches soon. For now that deb should be good!
