### ISSUE TITLE
Will this ever support EdgeRouters?

### ISSUE THREAD

**Issue by zimmertr** [davidnewhall/unifi-poller#133]
Hi, first of all thank you for making this! Amazing work, especially compared to traditional SNMP. 

Second of all, sorry for creating an issue for this. I wasn't sure what the best way to seek support would be. But, do you have any intentions of adding support for Edgerouter's in the future? Specifically the Edgerouter Lite?

**Comment by davidnewhall** [comment]
Simple answer: no

Edge devices do not use a UniFi controller, do not use the same API and do not provide data in the same format. They are essentially a different product; adding Cisco would be just as much work. Sorry this isn't the news you wanted.
