### ISSUE TITLE
docker image of pre-req

### ISSUE THREAD

**Issue by t3kg33k** [davidnewhall/unifi-poller#137]
I don't know that much about docker, I just started an online course to learn about it, but couldn't there also be a docker image of the prerequisites?

**Comment by davidnewhall** [comment]
They certainly can be! Grafana and InfluxDB both have docker images available. So does the UniFi controller! I've spoken with many people who run the whole stack in Docker.

**Comment by davidnewhall** [comment]
We even have a Docker Compose file available that makes it even easier to bring up all the containers (minus the controller). Check that out here: https://github.com/davidnewhall/unifi-poller/blob/master/init/docker/docker-compose.yml - there's some explanation of how to use it in the wiki. Please join us on Discord if you have more questions or need assistance settings things up!
