### ISSUE TITLE
unifi-poller error after 5.10.17 controller update.

### ISSUE THREAD

**Issue by mellow129** [davidnewhall/unifi-poller#14]
About two days ago I updated the unifi controller to 5.10.17
Now i'm seeing:
unifi-poller[10346]: unifi.GetUnifiDeviceAssets(): [0] json.Unmarshal([]USW): json: cannot unmarshal number into Go struct field .aggregated_by of type bool
at every interval.
Do you have any advice?

**Comment by mellow129** [comment]
I noticed some issues with the Unifi controller software and I restored a backup from 02/10/19. Same version of the controller, but unifi-poller seems to connect fine now. Closing the issue.
Apparently this wasn't an issue with the poller, but with the controller. Thank you!

**Comment by davidnewhall** [comment]
Sorry I never noticed your issue (since you closed it so quickly). If you're still having problems with the latest controller version, please let me know, and lets work it out. Thanks!

**Comment by davidnewhall** [comment]
I sorta think this has to do with disabled devices, and the bug is actually fixed now.
