### ISSUE TITLE
Missing values in variables

### ISSUE THREAD

**Issue by dktz** [davidnewhall/unifi-poller#140]
I'm on latest stable versions for InfluxDB, Grafana and your nice UniFi-Poller, all on debian OS. I have downloaded your dashboards and imported them. I selected InfluxDB as datasource in the import stage. All ok with import and now i can see your dashboards in Grafana. The problem is that the graps only shows values if the query isn't including any variables. I have double checked that all variables in the dashboards has the right datasource, but still no go.
Also the dropdowns on top-left (Site, AP, Switch and Client) do not have values exept "All" to choose from.
For me it seems as the dashboards values dont get the proper values from the datasource in Grafana.
Someone who have a solution for this issue? Or know how i can check the values for a parameter in Grafana. Like writing a direct query and see the result?

**Comment by davidnewhall** [comment]
Hello! Lets see if we can figure this out...

It sounds like the variable queries are not returning any results. Make sure your devices have names, unique names. The variable queries are shown in the variable configuration in the dashboard settings. Try running them directly in an `influx` session to see if any data returns. Run other influx `SHOW` and `SELECT` queries to see if the tables contain data. All of the examples are in the Grafana graphs themselves; in graph edit mode, you can toggle each query so it shows you the select statement it sends to Influx. Copy it and remove or replace the variables with values. Try without the variables. Try with fewer variables. Inevitably you'll find the missing pieces. Messing around with influx will help you learn and understand how it works. The query syntax is very similar to sql.

Does the unifi-poller log output show any error lines? Can you paste some of the log? It should show how many devices and clients it finds on each polling interval. If it's showing zeros something is wrong.

**Comment by dktz** [comment]
Thanks David for you fast reply. Everything is working as it should exept that the variable queries doesn't get any values. I have created new graphs based on the UniFi>InfluxDB data ans the poller is up and running each 30sec without any errors in the log. If i remove the parameterized values in the grap-query then the graph shows values.

I have also played around with the parameterqueries and it seem that they works and gives values in "Preview of values", but not for the ones inluded in the dashboards. Example of SITE query: SHOW TAG VALUES FROM "clients" WITH KEY = "site_name"  shows nothing from datasource Infux in "Preview of values". All devices have unique names.
I will try to play around more with the parameter-query and learn more about the syntax. Ill let you know if i find a solution.

**Comment by davidnewhall** [comment]
Are you saying the problem you're having is the site variable query is returning no results? And this only happens with the Client dashboard? The other dashboards show sites to choose from?

**Comment by davidnewhall** [comment]
Does the unifi-poller log output show any error lines? Can you paste some of the log?

**Comment by dktz** [comment]
There is no errors in the log.
Please check the last rows here...
danktz@computestick:~$ tail -f -n100  /var/log/syslog /var/log/messages | grep unifi-poller
tail: cannot open '/var/log/messages' for readingNov 18 18:53:50 computestick unifi-poller[603]: 2019/11/18 18:53:50 [INFO] UniFi Measurements Recorded. Sites: 1, Clients: 29, Wireless APs: 3, Gateways: 1, Switches: 4, Points: 116, Fields: 4095
Nov 18 18:54:20 computestick unifi-poller[603]: 2019/11/18 18:54:20 [INFO] UniFi Measurements Recorded. Sites: 1, Clients: 29, Wireless APs: 3, Gateways: 1, Switches: 4, Points: 116, Fields: 4095
Nov 18 18:54:50 computestick unifi-poller[603]: 2019/11/18 18:54:50 [INFO] UniFi Measurements Recorded. Sites: 1, Clients: 29, Wireless APs: 3, Gateways: 1, Switches: 4, Points: 116, Fields: 4095
Nov 18 18:55:20 computestick unifi-poller[603]: 2019/11/18 18:55:20 [INFO] UniFi Measurements Recorded. Sites: 1, Clients: 29, Wireless APs: 3, Gateways: 1, Switches: 4, Points: 116, Fields: 4095
Nov 18 18:55:50 computestick unifi-poller[603]: 2019/11/18 18:55:50 [INFO] UniFi Measurements Recorded. Sites: 1, Clients: 29, Wireless APs: 3, Gateways: 1, Switches: 4, Points: 116, Fields: 4095
Nov 18 18:56:20 computestick unifi-poller[603]: 2019/11/18 18:56:20 [INFO] UniFi Measurements Recorded. Sites: 1, Clients: 29, Wireless APs: 3, Gateways: 1, Switches: 4, Points: 116, Fields: 4095
: No such file or directory

**Comment by davidnewhall** [comment]
This sounds rather strange. It sounds like your data source is pointing to the wrong location. Can you tell me which graphs *are* working? What version of Influx?

**Comment by dktz** [comment]
Hi David.
Thanks for your time with my issue. In previous post i said that i had the latest versions of the different software, but it seems that i had an older version of influxdb installed. (It was the newest for Ubuntu, but i found a newer debian package on influx homepage) With the latest version of influx InfluxDB (version: 1.7.9) all parameters started to work. :) Once again, BIG thanks for your time!!!

**Comment by davidnewhall** [comment]
Great! I'm very glad it's working out for you!
