### ISSUE TITLE
unmarshal bool for USG 

### ISSUE THREAD

**Issue by ronzle** [davidnewhall/unifi-poller#15]
Hi, 

i get following error fur the USG gateway.
All other is working fine 

Controller version is 5.10.12

ERROR] 0: json.Unmarshal([]USG): json: cannot unmarshal bool into Go struct field .up of type string
[INFO] Logged Unifi States. Clients: 39 - Wireless APs: 3 Gateways: 0 Switches: 3
[ERROR] 0: json.Unmarshal([]USG): json: cannot unmarshal bool into Go struct field .up of type string
[INFO] Logged Unifi States. Clients: 39 - Wireless APs: 3 Gateways: 0 Switches: 3
[ERROR] 0: json.Unmarshal([]USG): json: cannot unmarshal bool into Go struct field .up of type string
[INFO] Logged Unifi States. Clients: 39 - Wireless APs: 3 Gateways: 0 Switches: 3
[ERROR] 0: json.Unmarshal([]USG): json: cannot unmarshal bool into Go struct field .up of type string
[INFO] Logged Unifi States. Clients: 39 - Wireless APs: 3 Gateways: 0 Switches: 3
[ERROR] 0: json.Unmarshal([]USG): json: cannot unmarshal bool into Go struct field .up of type string
[INFO] Logged Unifi States. Clients: 38 - Wireless APs: 3 Gateways: 0 Switches: 3
[ERROR] 0: json.Unmarshal([]USG): json: cannot unmarshal bool into Go struct field .up of type string
[INFO] Logged Unifi States. Clients: 39 - Wireless APs: 3 Gateways: 0 Switches: 3
[ERROR] 0: json.Unmarshal([]USG): json: cannot unmarshal bool into Go struct field .up of type string
[INFO] Logged Unifi States. Clients: 39 - Wireless APs: 3 Gateways: 0 Switches: 3
[ERROR] 0: json.Unmarshal([]USG): json: cannot unmarshal bool into Go struct field .up of type string
[INFO] Logged Unifi States. Clients: 39 - Wireless APs: 3 Gateways: 0 Switches: 3
[ERROR] 0: json.Unmarshal([]USG): json: cannot unmarshal bool into Go struct field .up of type string
[INFO] Logged Unifi States. Clients: 38 - Wireless APs: 3 Gateways: 0 Switches: 3
[ERROR] 0: json.Unmarshal([]USG): json: cannot unmarshal bool into Go struct field .up of type string
[INFO] Logged Unifi States. Clients: 38 - Wireless APs: 3 Gateways: 0 Switches: 3
[ERROR] 0: json.Unmarshal([]USG): json: cannot unmarshal bool into Go struct field .up of type string
[INFO] Logged Unifi States. Clients: 38 - Wireless APs: 3 Gateways: 0 Switches: 3

Thanks
Ronny

**Comment by ronzle** [comment]
here the according debug output 

2019/03/21 10:26:58.941175 main.go:102: [INFO] Everyting checks out! Beginning Poller Routine.
2019/03/21 10:27:29.001380 unidev.go:131: [DEBUG] Unmarshalling Device Type: ugw
2019/03/21 10:27:29.002234 unidev.go:138: [ERROR] 0: json.Unmarshal([]USG): json: cannot unmarshal bool into Go struct field .up of type string
2019/03/21 10:27:29.002912 unidev.go:131: [DEBUG] Unmarshalling Device Type: usw
2019/03/21 10:27:29.004849 unidev.go:131: [DEBUG] Unmarshalling Device Type: usw
2019/03/21 10:27:29.006683 unidev.go:131: [DEBUG] Unmarshalling Device Type: usw
2019/03/21 10:27:29.009242 unidev.go:131: [DEBUG] Unmarshalling Device Type: uap
2019/03/21 10:27:29.012347 unidev.go:131: [DEBUG] Unmarshalling Device Type: uap
2019/03/21 10:27:29.013980 unidev.go:131: [DEBUG] Unmarshalling Device Type: uap
2019/03/21 10:27:29.234665 main.go:116: [INFO] Logged Unifi States. Clients: 39 - Wireless APs: 3 Gateways: 0 Switches: 3

**Comment by davidnewhall** [comment]
Sorry just noticed your issue! Let me see if i can figure this one out... 👍

**Comment by davidnewhall** [comment]
`up` is normally true/false. Unfortunately I can't make the json library output the actually string that failed to parse. For now, can you look at the json payload and see what the value coming back for `up` is? I'm wondering if it's `"true"` or `"1"` or what... I'll try to fix this regardless of if you can find that output or not. Gimme a day or so.

**Comment by davidnewhall** [comment]
Crazy enough, there are five different `up` parameters in the USG output. I currently have one marked as `string` and the other four `bool`. I have a fix I can put in place, but it would be helpful if I knew what string value you're getting for all of your `up` outputs. I don't have an easy way to guide you to retrieving that, but it gives me a hankering to figure it out and write a troubleshooting page in the wiki. More to come.

**Comment by davidnewhall** [comment]
Please run `make deps` to download the latest `unifi` package. Then run `make` again to compile the binary. This should solve the problem you've reported. Thanks!
