### ISSUE TITLE
Field Type Conflict

### ISSUE THREAD

**Issue by christronyxyocum** [davidnewhall/unifi-poller#153]
Most, if not all, Docker image versions after 1.5.4 result in the following error being seen:

`2019/12/03 12:27:23 [INFO] Logging Measurements to InfluxDB at http://192.168.1.3:8086 as user unifi
2019/12/03 12:27:23 [ERROR] processing metrics: influxdb.Write(points): {"error":"partial write: field type conflict: input field \"channel\" on measurement \"uap_vaps\" is type integer, already exists as type float dropped=4"}
2019/12/03 12:27:23 [ERROR] influxdb.Write(points): {"error":"partial write: field type conflict: input field \"channel\" on measurement \"uap_vaps\" is type integer, already exists as type float dropped=4"}`

I was on the stable tag for months without issues until I updated the image today.

**Comment by davidnewhall** [comment]
Docker Cloud is building a new image. Can you try the `latest` tag in about 30 min?

**Comment by christronyxyocum** [comment]
No worries, I know how the development process can be. I deleted and recreated the DB, pulled the new image, and things seem to be working now. Thanks for the quick reply and support.
