### ISSUE TITLE
"error":"partial write: field type conflict

### ISSUE THREAD

**Issue by junior466** [davidnewhall/unifi-poller#156]
After the most recent update `1.6.2`, I am receiving the following errors:

        unifi-poller[9775]: 2019/12/09 09:48:28 [ERROR] processing metrics: influxdb.Write(points): {"error":"partial write: field type conflict: input field \"channel\" on measurement \"uap_vaps\" is type float, already exists as type integer dropped=12"}
        unifi-poller[9775]: 2019/12/09 09:48:28 [ERROR] influxdb.Write(points): {"error":"partial write: field type conflict: input field \"channel\" on measurement \"uap_vaps\" is type float, already exists as type integer dropped=12"}

edit - And thank you for your hard work!

**Comment by davidnewhall** [comment]
Which version where you using before 1.6.2?

**Comment by davidnewhall** [comment]
There were some changes to this code in 1.6.0 and again in 1.6.1. It unfortunately made some incompatibilities. The only real fix is to drop the DB and recreate it.
```
$ influx
> DROP DATABASE unifi
> CREATE DATABASE unifi
```

**Comment by junior466** [comment]
> Which version where you using before 1.6.2?

I was on 1.6.1-576. I will do as you suggested.

Thank you.

**Comment by junior466** [comment]
By the way, since the error was on the measurement uap_vaps, I was able to only drop that measurement with `drop measurement uap_vaps ` and so far no errors :-)

Thank again for your help and hard work.

**Comment by davidnewhall** [comment]
Great tip, thanks!!
