### ISSUE TITLE
import grafana dashboards

### ISSUE THREAD

**Issue by keesnobel** [davidnewhall/unifi-poller#19]
I cant import the dashboards into grafana 

This error shows it

Import failed
JSON -> JS Serialization failed: Unexpected token < in JSON at position 6

**Comment by keesnobel** [comment]
> I cant import the dashboards into grafana
> 
> This error shows it
> 
> Import failed
> JSON -> JS Serialization failed: Unexpected token < in JSON at position 6

my bad i imported it the wrong way....

**Comment by davidnewhall** [comment]
Glad you got it worked out. I see you committed a couple changes in your fork. Those looks good. I'll make sure they're in my updates. I have put a lot of work into these dashboards, so I'll see about dropping at least a new "version" in here soon.

**Comment by davidnewhall** [comment]
I've pushed new dashboards with new features. Consider upgrading and giving it a go!
