### ISSUE TITLE
Feature Request: docker image [help requested]

### ISSUE THREAD

**Issue by mvillarejo** [davidnewhall/unifi-poller#20]
hello,
Great idea! wondering if you have thought about packing the app into a docker image?
thanks

**Comment by davidnewhall** [comment]
I noticed a lot of people going that route on the forums I linked in the README, using the telegraf/snmp implementation. Honestly, I'm sure someone else already built that wheel and I'd accept that contribution. If someone has already done this with telegraf, it should be reasonably easy to replace telegraf with a different go app (this one).

I personally don't have enough experience with docker to bust out a solid solution for the masses. Happy to leave this open as a feature request.

**Comment by davidnewhall** [comment]
Now that the releases are packages into deb/rpm files, I think a docker image is pretty easy. It's probably as simple as a Dockerfile that downloads a released file. I still am not the guy with the skills to do that and make sure it works properly.

**Comment by mabunixda** [comment]
@davidnewhall what configuration can be made via env variables? 
I only saw, that UNIFI_PASSWORD is referenced in up.conf.example ...

What is the prefered way to configure unifi-poller?

**Comment by davidnewhall** [comment]
The entire configuration is done in the config file. The only item that works via environment variable is `UNIFI_PASSWORD` - this allows one to use a secret management system that doesn't store the password on disk. That said, I'm up for feature requests if you think there are other/better ways to configure the app for Docker. I work best from examples, so if there's another app you can point at and say "they do it well" I'd be happy to check it out.

> What is the prefered way to configure unifi-poller?

Coming from a solid operational background, the answer to this question is simply: using a config management solution like puppet, chef, ansible or saltstack. Now that might work out for companies with an operations team, but I assume many people using this app are at home, at a school or a very small business with few extra servers to spare. That said, all you need to do to configure the app is put `up.conf` in the right place with the right credentials in the file. Keep a copy of that file and make it easy to redeploy when needed.

Please let me know your thoughts. Thank you for the Docker contribution!

Warm Regards,
-david

**Comment by davidnewhall** [comment]
A docker image is now available. [See the guide.](https://github.com/davidnewhall/unifi-poller/wiki/Docker)
