### ISSUE TITLE
Centos7 install

### ISSUE THREAD

**Issue by doc-jay** [davidnewhall/unifi-poller#30]
Trying to install this package on a CentOS 7 install and I'm getting

`rpm -Uvh unifi-poller-1.2.2-106.x86_64.rpm
Preparing...                          ################################# [100%]
        package unifi-poller-1.2.2-106.x86_64 is intended for a different operating system
`

**Comment by davidnewhall** [comment]
Hi Jay,
I have yet to really give the rpm much testing. I'm building it with fpm in a reasonably generic manner. I'll throw a centos install into a vbox and see what sorta fixes I can come up with. Thank you for the report!

**Comment by davidnewhall** [comment]
Found the problem. I'll cut anther release tonight that works on RedHat variants. Sorry about that!

**Comment by doc-jay** [comment]
Excellent - thanks for looking into this

**Comment by davidnewhall** [comment]
Have you given it a try yet? :D Did it work okay?

**Comment by doc-jay** [comment]
yes, it installed okay.  Now I just need to finish going through the installation guide.

Thanks!

**Comment by doc-jay** [comment]
Okay, read through your wiki.  It was the first time for me ever using Grafana and influxDB.  This is just me nitpicking, but maybe in your install wiki, at the beginning have a section of 'Prerequisites'?  List out:
1.  Grafana
2.  Grafana plugins
3:  influxDB

Here is the link I used to install Grafana for Centos7 (https://grafana.com/docs/installation/rpm/)
Here is the link I used to install influxDB for Centos7 (https://computingforgeeks.com/install-grafana-and-influxdb-on-centos-7/)

I found a typo on your page [here](https://github.com/davidnewhall/unifi-poller/wiki/Grafana-Dashboards) 'The package installs them into /usr/share/doc/uniti-poller' it's just with the word 'unifi'.

Great job on all of your hard work!  This is a ton of info to look at in Grafana.  I manage about 6 different sites and this is very useful info.  Now let me try to wrap my head around it!

**Comment by doc-jay** [comment]
Yes it worked!  I left some comments on the closed issue.  All running good.  

Thanks

On June 10, 2019 12:14:39 PM CDT, David Newhall II <notifications@github.com> wrote:
>Have you given it a try yet? :D Did it work okay?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/davidnewhall/unifi-poller/issues/30#issuecomment-500500435

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by davidnewhall** [comment]
Great feedback! Thank you! I'm excited you got everything working! Please crack open a new Issue if I can help out with anything else. I may not see your comments here, things have gotten pretty crazy; a lot of interest. Thanks again!

**Comment by davidnewhall** [comment]
Typo fixed. You're welcome to edit wiki pages too, anyone can! I also added your links to the Grafana and InfluxDB wiki pages. Added two more steps to prereqs. Thanks!
