### ISSUE TITLE
Unifi 5.6.40: Missing channel utilization and user count (num_sta) graph data

### ISSUE THREAD

**Issue by tronotoc** [davidnewhall/unifi-poller#32]
Hello, 

just want to say thank you and give you the feedback, that some metrics on uap-ac-lite are missing, e.g. channel, clients, etc. 

![UniFi UAP Insights - Grafana](https://user-images.githubusercontent.com/14870475/59305437-8eca8500-8c9a-11e9-8427-95d6a465e24f.jpg)

**Comment by davidnewhall** [comment]
Looks like you're missing channel utilization and client count. 

Try editing the client graph and changing `num_sta` to `user-num_sta`. See if that makes the data show up. Please reply and let me know.

The channel utilization graph is actually 3 different metrics and all of them appear missing from your setup. I'll try to get a new feature into the app to make it easy to dump the json payload from the unifi controller. This would all you to see what the controller is returning for `cu_self`. I'd guess it's either missing of empty. I'm not sure if the AP has this measurement or if they renamed or removed it. Inspecting the raw json output from the controller should give us these clues. If you know how to do that, please give it a go, otherwise wait for an update to give us this debug info.

Thank you for your report! Please let me know what you're able to figure out, and we'll get this sorted soon!

**Comment by tronotoc** [comment]
In Grafana neither the field num_sta nor user-num_sta exists. 
Please let me know how to dump the json payload from unifi-controller. 

Thanks.

**Comment by tronotoc** [comment]
Just want to mention, that on dashboard unifi-clients-insight i can see all clients.

**Comment by davidnewhall** [comment]
Give me a day or two to get a new release out that has a feature making it easy to dump the json payload. I'm currently working on some other build-pipeline features and updates.

**Comment by davidnewhall** [comment]
Hi @tronotoc,

I've released unifi-poiler version 1.3.0. This update provides a new feature that allows you to print out the json payload from the Unifi controller. This is definitely not a solution to your missing data, but it may help us figure out "where" it is. To run the app in this mode, pass `-j devices` on the cli. Something like this:
```shell
unifi-poller -c /etc/unifi-poller/up.conf -j devices
```
If you have more than one site, it will help to specify only a single site in the up.conf config. Dumping data for multiple sites at a time is probably too much. These json payloads are large.

I'd recommend piping it through `jq` and into a file, so you can inspect it more closely:
```shell
unifi-poller -c /etc/unifi-poller/up.conf -j devices | jq | tee /tmp/unifi-device-data.json
```

Once you have this data, you have a few options:
1. Figure out where your client counter is. On my APs it's called `num_sta`.
1. Look for `cu_self` and try to figure out if they're empty or missing or renamed.
1. Remove any personal info from the file and put it in a [gist](https://github.com/gist) you can share with me, or attach it to this issue.

I'm sorry I don't have any real concrete advice for you. I've not had the opportunity yet to troubleshoot missing data like this. I'm just at a bit of a loss, and I'm hopeful it's an easy fix once I see your json. It may not be easy to understand this file if you're not familiar with Golang but I'll point out that it shows all the `fields` being stored in Influx from the UAPs.  Compare these fields with the data returned by your controller to determine if things are missing or renamed. https://github.com/golift/unifi/blob/master/uap_influx.go

Looking forward to your update. Good luck!

**Comment by mabunixda** [comment]
@tronotoc what version of unifi controller are you running?

I also got a UAP-AC-Lite installed and my dashboard is filled with values at version 1.3.0

**Comment by tronotoc** [comment]
@mabunixda 5.6.40 in docker container

**Comment by davidnewhall** [comment]
@tronotoc curious if you installed the plugins? See here: https://github.com/davidnewhall/unifi-poller/wiki/Grafana

**Comment by davidnewhall** [comment]
I'm betting this data doesn't actually exist in the same format in controller 5.6. That's the previous release. Most of us are running 5.10 and it seems good there. If you're not running older devices, try an upgrade. If you are running older devices, this may be one of the consequences. If you want to give me your json payloads I can investigate further. Thanks!

**Comment by tronotoc** [comment]
Thank you very much, after updating to 5.6.10 everything works. Great Job!

**Comment by davidnewhall** [comment]
Sorry, which version did you update to? You said `5.6.10`, but you were running `5.6.40` before?  Did you mean to say you upgrade to 5.10.x?

**Comment by tronotoc** [comment]
You’re right. 5.10.25

**Comment by davidnewhall** [comment]
If there is interest in supporting controller version 5.6, please provide the output of the following commands. These print out the json payloads from the controller. Having this data will allow me to make the app work with it.

Please scrub any private data (IPs, MACs, serials, etc) if you want. Attach the files here, or in a gist. Use the correct path to your config file.

```shell
unifi-poller -c /etc/unifi-poller/up.conf -j device
unifi-poller -c /etc/unifi-poller/up.conf -j client
unifi-poller -c /etc/unifi-poller/up.conf -j "other /api/stat/sites"
unifi-poller -c /etc/unifi-poller/up.conf -j "other /status"
```

If the client or device commands do not produce data, try this instead:
```shell
unifi-poller -c /etc/unifi-poller/up.conf -j "other /api/s/default/stat/device"
unifi-poller -c /etc/unifi-poller/up.conf -j "other /api/s/default/stat/sta"
```
