### ISSUE TITLE
USG WAN2 metrics missing.

### ISSUE THREAD

**Issue by mabunixda** [davidnewhall/unifi-poller#40]
Hi,

I found wan1_* metrics, but these clone the wan_* metrics - at least for tx/rx data :-(
Do you got any reports about that ?

Thanks

**Comment by davidnewhall** [comment]
Sorry, I'm not understanding the problem you're describing. Are you missing some data? wan2 perhaps? I have not had any other reports about the USG WAN metrics. I only have a USG3 w/ a single WAN, so I'm not quite sure what other configurations look like.

**Comment by davidnewhall** [comment]
I think I might get what you're asking now. The USG can have 2 WANs but only has 1 by default. If you look at the unifi [library code here](https://github.com/golift/unifi/blob/master/usg_influx.go#L76-L122) you'll see that all the `wan1` and `wan` metrics are "different," but in your case, and in my case, the numbers provided are identical. This is because we only have 1 gateway. My assumption (without testing a second gateway) is that the `wan` metrics would include `wan1` and `wan2`. We don't have wan2 so wan is equal to wan1. 

I've never pulled data from a controller that has a gateway with two WANs and I do not know what the JSON looks like. I can guess, and if someone raises an issue or feature request for WAN2 metrics I'll work with them to test some changes that expose the data.

Let me know your thoughts!

Thanks,
-david

**Comment by davidnewhall** [comment]
The dang docker build failed to trigger when I pushed a new release. ugh . haha I'm going to have to set it up on my test repo and figure out how to make it work. 🔢

**Comment by davidnewhall** [comment]
unrelated to this request, and going back to our previous interaction: Finally got Docker to build a tagged release. yay. I also updated the wiki: https://github.com/davidnewhall/unifi-poller/wiki/Docker -would like to know what you think!

**Comment by davidnewhall** [comment]
Try running Unifi-poller with the `-j` option to print out the controller json payload for your devices. Something like:
```shell
unifi-poller  -c /etc/unifi-poller/up.conf -j devices | jq . > devices.json
```
This dumps the output from the controller directly. Check for the wan and wan1 data in the output. I'm guessing they match. This shows a little bit of my data, take note the rx_bytes are the same.
```
unifi:~ admin$ unifi-poller -j devices -c/usr/local/etc/unifi-poller/up.conf|jq|grep -A10 wan
[INFO] Authenticated to Unifi Controller @ https://127.0.0.1:8443 as user influxdb
[INFO] Dumping Device JSON for site Home (default)
      "wan1": {
        "tx_bytes-r": 112126,
        "rx_bytes-r": 2017642,
        "bytes-r": 2129769,
        "max_speed": 1000,
        "type": "wire",
        "name": "wan",
        "ifname": "eth0",
        "ip": "67.x.x.x",
        "netmask": "255.255.254.0",
        "mac": "f0:9f:c2:c4:ab:0f",
        "up": true,
        "speed": 1000,
        "full_duplex": true,
        "rx_bytes": 1204512944833,
        "rx_dropped": 19622,
        "rx_errors": 0,
--
          "name": "wan",
          "ifname": "eth0",
          "ip": "67.x.x.x",
          "netmask": "255.255.254.0",
          "mac": "f0:9f:c2:c4:bb:f0",
          "up": true,
          "speed": 1000,
          "full_duplex": true,
          "rx_bytes": 1204512944833,
          "rx_dropped": 19622,
          "rx_errors": 0,
```

**Comment by mabunixda** [comment]
Hi,

now not the same result on my site:
```json
      "wan1": {
        "tx_bytes-r": 1569,
        "rx_bytes-r": 6428,
        "bytes-r": 7998,
        "max_speed": 1000,
        "type": "wire",
        "name": "wan",
        "ifname": "eth0",
        "ip": "192.168.20.3",
        "netmask": "255.255.255.0",
        "mac": "xxx",
        "up": true,
        "speed": 100,
        "full_duplex": true,
        "rx_bytes": 90145175388,
        "rx_dropped": 0,
        "rx_errors": 0,
        "rx_packets": 76469136,
        "tx_bytes": 8937607648,
        "tx_dropped": 0,
        "tx_errors": 0,
        "tx_packets": 46097337,
        "rx_multicast": 595261,
        "enable": true,
        "dns": [
          "172.16.20.5",
          "1.1.1.1"
        ],
        "gateway": "192.168.10.1"
      },
```
and for wan2
```json
      "wan2": {
        "tx_bytes-r": 390,
        "rx_bytes-r": 453,
        "bytes-r": 843,
        "max_speed": 1000,
        "type": "wire",
        "name": "lan2",
        "ifname": "eth2",
        "ip": "192.168.10.3",
        "netmask": "255.255.255.0",
        "mac": "xxx",
        "up": true,
        "speed": 100,
        "full_duplex": true,
        "rx_bytes": 52963722747,
        "rx_dropped": 0,
        "rx_errors": 0,
        "rx_packets": 41770249,
        "tx_bytes": 6089947738,
        "tx_dropped": 0,
        "tx_errors": 0,
        "tx_packets": 25126762,
        "rx_multicast": 745876,
        "enable": true,
        "dns": [
          "172.16.20.5",
          "1.1.1.1"
        ],
        "gateway": "192.168.10.1"
      }
```
Your grep command show the "wan1" tag and the "name": "wan" lines. 
Can you grep for "ifname": "eth0/eth2" is this is present in your dataset?
I guess the eth2 metrics are not sent to the influxdb

**Comment by davidnewhall** [comment]
This is my original question.
> Are you missing some data? wan2 perhaps?

I think you just answered it. Thank you!

**Comment by mabunixda** [comment]
Yes, wan2 ist not available. But wan and wan1 are equal




On Mon, Jun 17, 2019 at 7:10 PM +0200, "David Newhall II" <notifications@github.com> wrote:












This is my original question.



Are you missing some data? wan2 perhaps?



I think you just answered it. Thank you!

**Comment by davidnewhall** [comment]
The next release will include `wan2` measurements.

**Comment by davidnewhall** [comment]
Could you do me a huge favor? Export your json again, like you did earlier, and paste it into this website https://mholt.github.io/json-to-go/ - that will output a Golang structure on the right. Please copy/paste that AutoGenerated struct into this issue. I do not have a second wan, so my json lacks the data. I just want to make sure I do this correctly and it works the first time. :D Thanks!

**Comment by davidnewhall** [comment]
New release has wan2 in influxdb. No graphs for it though. Good luck!
