### ISSUE TITLE
Dashboards not populating

### ISSUE THREAD

**Issue by rjchu** [davidnewhall/unifi-poller#41]
I’ve built and installed the pillar as a package and I’m getting data for the usw dashboard but the other 3 are blank - they don’t seem to even have blank panels. I imported the json files directly ba copy/paste so there shouldn’t be any user error there. I’m running a USG, NanoHDs and a couple 24 port switches. Given that I see screenshots here from other users I know it’s an error on my part I’m just not sure what as there’s data flowing as evident by the usw dashboard working. 

Thanks,

-joni-

**Comment by davidnewhall** [comment]
Can you attach a screenshot of one or more of the empty dashboards? Your description of " they don’t seem to even have blank panels" makes me think this is a problem with grafana or the dashboards as opposed to a data-missing problem.  

Questions:

- What version of Grafana are you running? (Can you upgrade to 6.2+ if you're not there?)
- Did you install the plugins? See  the bottom of https://github.com/davidnewhall/unifi-poller/wiki/Grafana for plugin info.
- Are you familiar enough with grafana to edit the (missing??) blank panels and see what data points are available? 
- Are you familiar enough with InfluxDB to see if the data is there?  Something like:
```
$ influx
Connected to http://localhost:8086 version v1.7.6
InfluxDB shell version: v1.7.6
Enter an InfluxQL query
> use unifi
Using database unifi
>  SHOW MEASUREMENTS
name: measurements
name
----
clients
uap
uap_radios
usg
usg_networks
usw
usw_ports
> select * from uap_radios where time > '2019-06-15'
```
The last command should show some data. You can do similar selects against the other tables.

Let me know what you find. Thanks!
-david

**Comment by rjchu** [comment]
David,

I was using the instructions located at github.com/davidnewhall/unify-poker/wiki/Installation and try as I might I can’t find any mention of these plugins being needed there. Having said that, I’ve now installed them and all 4 example dashboards are working! The UAP dashboard is mostly populated aside from the 6 panels right below the first panel (AP Details) but I think this is because I have 3 AP’s. If I select any one of them instead of all then those panels populate with data as well. 

Glad it was a simple fix, oversight on my part as I didn’t know about the plugins. Thanks for your quick reply and for sharing this with the community!

-joni-

**Comment by davidnewhall** [comment]
Thanks for the reply and details! I'm very happy it's working for you! The documentation is definitely a work in progress, and I'll be sure to address the situation you ran into. It's also good to know what happens when the plugins are not installed. haha, good stuff. 

As for those empty panels, that's normal. They can only populate when you select one AP. 

You're encouraged to make your own dashboard. Copy these panels into a dashboard that has the things that are interesting to you. If you like those single stat panels, you can recreate them for each AP on another dashboard.

Thanks again and good luck!
-david
