### ISSUE TITLE
Missing data on dashboard UniFi UAP Insights

### ISSUE THREAD

**Issue by doc-jay** [davidnewhall/unifi-poller#43]
Just updated to v1.3.1 and on the dashboard "UniFi UAP Insights', the values are not showing up for the six boxes under the 'AP Details' table that show radio channels, TX Power, CPU usage, Uptime.

**Comment by davidnewhall** [comment]
uh oh. looking.

**Comment by davidnewhall** [comment]
That might be normal. Do you have more than one AP? Those panels can only populate when you have 1 WAP selected in the variables at the top. More explanation here: https://github.com/davidnewhall/unifi-poller/issues/41#issuecomment-502335283

Lemme know if it works with one AP selected :D

Thanks,
-david

**Comment by doc-jay** [comment]
yes, it works now that I have one AP selected.  Thanks for showing me that, how else could it work anyways?!

**Comment by davidnewhall** [comment]
I made some nice changes to the Unifi UAP Insights Dashboard, check it out!
