### ISSUE TITLE
UniFi Sites dashboard only shows 1 site.

### ISSUE THREAD

**Issue by doc-jay** [davidnewhall/unifi-poller#45]
I'm totally new to Grafana.  I was using your new dashboard and I have multi-sites.  I noticed there wasn't a drop down to pick different sites, so I edited your variable '$site' and just selected the 'multi-value' and 'Include All option' and I can now pick different sites.  Also, I noticed your other dashboards have the variable as '$Site', and if I would change it on this new dashboard to match it, then I would get no data, so I changed it back to '$site'.

Also, on the 'Data Transfer' and 'Client Counts' panels, it didn't list the site name there because I think the title of the panel was 'Site $Site Data Transfer' for example, so I changed it to match the variable of '$site' as in 'Site $site Data Transfer' and it then displayed the name of the site correctly.  I did this for the 'Client Counts' panel as well.

Hope that is clear as mud :-).

Nice work on your dashboard!  Can't wait until you get the one ready that shows the stats of the modem, I'm using ATT Fiber so I'm not sure how that would work out for me since I'm bypassing it with my EdgeRouther 6P.

**Comment by davidnewhall** [comment]
This is good feedback. I setup the Sites dashboard so it should repeat the panels for every site. In other words, I expect all sites to show up all the time. Is that not what happened for you?

I specifically named the variable `site` instead of `Site` so the links would work properly and not try to set `site` to `All` (which made the dashboard not work correctly for me).

**Comment by davidnewhall** [comment]
I just re-read what you said. All you did was fix the panel titles that said `$Site`. hm. That's all I did in the dashboard I attached. I'm confused why they are not repeating for you. :( I may have to stick some fake data into my influx to try to show > 1 site..

**Comment by doc-jay** [comment]
@davidnewhall when I imported your dashbaord, only one site was displaying for me.  I couldn't find a way to choose different sites so I was looking for a drop down like your other dashboards provided.  

I can do further testing for you later if you think you have it working the way you intended.

**Comment by doc-jay** [comment]
about this comment:

> Can't wait until you get the one ready that shows the stats of the modem

I was referring to a post on the UniFi community stories where I had this user confused with you, and used your project to make his own dashboard [here](https://community.ubnt.com/t5/UniFi-Stories/The-Pool-Bar/cns-p/2794831) - sorry for the confusion.   I gotta figure out how to get that info into grafana!

**Comment by davidnewhall** [comment]
Good stuff, thanks for the update and screenshot! I'm going to have to mess with this some more on my end and try to figure out what's going on. The entire collapsable row should be repeating all 24 graphs for every site. Gimme a few to figure it out. One question: when you select "all" (after your edits), does it show all sites, or only one shows up still?

As for the modem graphs, that forum link is cool. He wrote a script that pulls data out of the modem and puts it into Influx. Honestly, sounds simple, but I don't know how to access my arris cable modem through the router. Just not sure how. Hopefully that script gets released and you can make use of it!

**Comment by davidnewhall** [comment]
I can't seem to import the dashboard because it wants mysql? Not real sure, trying to figure it out.

**Comment by davidnewhall** [comment]
Found the problem. The fixed dashboard will be in master shortly. Thanks for your report!
