### ISSUE TITLE
better muti AP graphs, dashboard and screenshot included

### ISSUE THREAD

**Issue by zunder1990** [davidnewhall/unifi-poller#46]
This is based on a older version of the poller but I hope that the graphs will give you ideas on the type of charts that are good when you have many APs. This is what I used an event with 15 APs

json
https://pastebin.com/1EX64Xbe

screenshot 
https://snapshot.raintank.io/dashboard/snapshot/57buZAZaYtSb0TnxBae8HjmBFW2ckVEh

**Comment by davidnewhall** [comment]
sick. Thanks!

**Comment by davidnewhall** [comment]
Alright I got it to import. I renamed a few things, and I notice it broke your dashboard. When you upgrade unifi-poller you'll have to edit a few graphs. Some metrics now begin with `vap_`. Should be pretty easy for you to do. I'll get some new graphs into the included UAP dashboard, thanks again for this!

**Comment by zunder1990** [comment]
The system with the database and poller was only used for the event and is now offline. I will be installing the new version of the poller and keep working on better muti ap support.

**Comment by davidnewhall** [comment]
Sounds good! I incorporated a number of your graphs into the Unifi UAP Insights dashboard. I will merge it into master soon and you can try it out; let me know what you think!

**Comment by davidnewhall** [comment]
The changes have been merged into master. Please let me know what you think when you have a chance to test it out. Thanks!
