### ISSUE TITLE
New installs overwriting the 'up.conf' file

### ISSUE THREAD

**Issue by doc-jay** [davidnewhall/unifi-poller#58]
Would be useful if when updating for Linux (not sure how it works for other OS install packages for unifi-poller) that the installer would not overwrite my 'up.conf' file.  I've started making a backup of it in the '/etc/unifi-poller' dir and just overwrite the new file with my backup.

**Comment by davidnewhall** [comment]
uh oh. That should not be happening and I can totally fix it. Are you using a deb or rpm?

**Comment by doc-jay** [comment]
.rpm

**Comment by davidnewhall** [comment]
on it.

**Comment by davidnewhall** [comment]
Are you able to test that branch out?

**Comment by davidnewhall** [comment]
It seems to correct the problem on my test instance. The next package released should be "fixed."

**Comment by doc-jay** [comment]
thanks, I'll test with your next release, we can close this for now.  Thanks for taking care of this so quickly 👍
