### ISSUE TITLE
json: cannot unmarshal string into Go struct field UAP.uptime of type float64

### ISSUE THREAD

**Issue by emnaz** [davidnewhall/unifi-poller#6]
Hi,

I have a problem with unifi-poller. 

Error message:
`Polling Unifi Controller, interval: 30s
unifi.GetUnifiDeviceAssets(): [31] json.Unmarshal([]UAP): json: cannot unmarshal string into Go struct field UAP.uptime of type float64`

Please advice.

Thanks

**Comment by davidnewhall** [comment]
I merged a contribution that should resolve this error. Please try again with the latest version in the master branch. Please let me know if that works or if any other errors pop up. Thanks!

**Comment by davidnewhall** [comment]
If it works out feel free to close this issue.
