### ISSUE TITLE
Docker on pi

### ISSUE THREAD

**Issue by garandotorg** [davidnewhall/unifi-poller#66]
I'm trying to get the docker image running on my Raspberry Pi running Raspbian Stretch but when I start the docker container it exits immediately with:

standard_init_linux.go:211: exec user process caused "exec format error"

I think it's because the architecture for docker is locked to amd64 rather than armv6 or armv7 but I've only been playing with docker for a couple of days so I'm still learning.

**Comment by davidnewhall** [comment]
Hello!

I was actually looking into multi-architecture Docker support shortly after the 1.4.0 release where we've added some preliminary arm/rpi support. I spent a good hour investigating what would be needed, and you beat me to this issue. :D I still trying to figure it all out, and I'll update this issue as soon as I have more knowledge on the subject.

Open to pointers, tips and tricks on how to convert a normal linux Docker image to multi-arch. I was looking for a recent "howto switch" article and couldn't really come up with one. I'm still very new to Docker and don't personally run any containers.

**Comment by davidnewhall** [comment]
Can you try this? 
```shell
docker pull golift/unifi-poller:latest_linux_arm
```
Lemme know! Thanks!

**Comment by garandotorg** [comment]
Hi David,

Thanks for your help.

I’m now getting a permissions error.  Trying to work out how to build an environment I can test in but I’m new to docker too - getting Grafana/InfluxDb/Telegraf and now your poller to work is my project to get me started on docker.

docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/unifi-poller\": permission denied": unknown.

Cheers,

Garan.

**Comment by davidnewhall** [comment]
That seems so odd. I've been pushing new `latest` tags for the past few hours, maybe one of these commits will fix it. hah. I'm googling trying to figure out what can cause that particular error...

**Comment by davidnewhall** [comment]
Figured it out. `ARG`s must be specified in each build stage. Try `latest` again in about 15-20 minutes after it finishes building.

**Comment by garandotorg** [comment]
Thanks for all of your help David and I’ve got it all working now. 

I was getting a connection refused to get to my docker contained InfluxDB so I’m now using the following line to start my container with the —net=host line being key:

docker run --restart unless-stopped --detach --net=host --name=unifi-poller -v /<path to my directory>/up.conf:/etc/unifi-poller/up.conf golift/unifi-poller

Cheers,

Garan.

**Comment by davidnewhall** [comment]
Nice! That's good info, I'll add it to the Docker wiki. Please let me know if you run into any other problems, happy to help!
