### ISSUE TITLE
Error starting docker container

### ISSUE THREAD

**Issue by Waffull** [davidnewhall/unifi-poller#70]
Getting the following error when starting the docker container:

> mschauber@minipc:~$ sudo docker run -d -v /your/config/up.conf:/etc/unifi-poller/up.conf golift/unifi-poller:stable
2746052ab4e061e8bbc73936987b903b5bfd929725a0276be7182a2788958b02
docker: Error response from daemon: error while creating mount source path '/your/config/up.conf': mkdir /your: read-only file system.

**Comment by davidnewhall** [comment]
`/your/config/up.conf` in the startup command should be replaced with a path on your docker host that exists. This is how you pass a unifi-poller config file (up.conf) to the docker container.

**Comment by Waffull** [comment]
I was lazy, instead of changing the docker command line, I just created the /your/config/ structure and put up.conf in there.  Or does that path have to be inside one of the existing docker folders?

**Comment by davidnewhall** [comment]
That path can be anywhere you want. I wouldn't recommend `/your`, but that works. Something like `/etc/unifi-poller` may work better. I don't use Docker enough to provide solid advice, but there's probably an appropriate place in the Docker folder structure to put container config files; I'd look into that possibility.

**Comment by davidnewhall** [comment]
Please let me know if I can provide any more assistance!
