### ISSUE TITLE
Manual install/build path problem

### ISSUE THREAD

**Issue by Waffull** [davidnewhall/unifi-poller#74]
Trying to build the updated armhf package.

I've hit a brick wall with all the googling.... can't find an answer.
running 
> git clone https://github.com/davidnewhall/unifi-poller.git

puts it in $HOME/unifi-poller

go env results in:
> mschauber@minipc:~/unifi-poller$ go env
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/mschauber/.cache/go-build"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOOS="linux"
> GOPATH="/home/mschauber/go"
> GOPROXY=""
> GORACE=""
> GOROOT="/usr/local/go"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
> GCCGO="gccgo"
> CC="gcc"
> CXX="g++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build003868689=/tmp/go-build -gno-record-gcc-switches"

Trying to create the build, results in:

> mschauber@minipc:~/unifi-poller$ make armhf deb
> # Building linux 32-bit ARM binary.
> GOOS=linux GOARCH=arm GOARM=6 go build -o unifi-poller.armhf.linux -ldflags "-w -s -X github.com/davidnewhall/unifi-poller/unifipoller.Version=1.4.2"
> main.go:6:2: cannot find package "github.com/davidnewhall/unifi-poller/unifipoller" in any of:
>         /usr/local/go/src/github.com/davidnewhall/unifi-poller/unifipoller (from $GOROOT)
>         /home/mschauber/go/src/github.com/davidnewhall/unifi-poller/unifipoller (from $GOPATH)
> Makefile:106: recipe for target 'unifi-poller.armhf.linux' failed
> make: *** [unifi-poller.armhf.linux] Error 1

*No idea why that one line is large and bold.

Anyway, not being all that familiar with go, I've tried playing around with different GOPATHs and moving the unifi-poller folder, all without any luck. Any help would be greatly appreciated.

**Comment by davidnewhall** [comment]
Alrighty! We can fix this. Go is very picky about folder paths, and they are used to name space things. In other words, libraries are imported by their path.  it's even giving you a clear hint:
> /home/mschauber/go/src/github.com/davidnewhall/unifi-poller/unifipoller (from $GOPATH)

This should get you working (assuming you haven't changed any poaths since you opened this issue):
```shell
mkdir $GOPATH/src/github.com/davidnewhall
mv ~/unifi-poller $GOPATH/src/github.com/davidnewhall
cd $GOPATH/src/github.com/davidnewhall/unifi-poller
make dep
make debarmhf
```

If you haven't installed dep, do that first. It's really easy, copy/paste the install.sh snippet [from here](https://golang.github.io/dep/docs/installation.html).

**Comment by Waffull** [comment]
I had, I thought, done that.  But I tried so many different variations, who knows.
FYI, I had to mkdir .../github.com before I could mkdir .../github.com/davidnewhall

Upon running make dep, I get the following error:

> go get github.com/github/hub/md2roff-bin
> make: go: Command not found
> Makefile:73: recipe for target 'md2roff' failed
> make: *** [md2roff] Error 127

Current go env:

> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/mschauber/.cache/go-build"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOOS="linux"
> GOPATH="/home/mschauber/go"
> GOPROXY=""
> GORACE=""
> GOROOT="/usr/local/go"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
> GCCGO="gccgo"
> CC="gcc"
> CXX="g++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build320175043=/tmp/go-build -gno-record-gcc-switches"

**Comment by davidnewhall** [comment]
> make: go: Command not found

`go` is not found. 

Can you run `go`? Make sure it's in your path? I'm not sure what else here.

**Comment by Waffull** [comment]
I saw that, but I was able to run "go env"...  so it's clearly in the
path.  I'll try and play around some more later.

Are builds with the fixes from yesterday going to be rolled out?  I'm not
anticipating getting this darn compile process running properly :(

**Comment by davidnewhall** [comment]
That deb I attached to the other issue should get you working? I've been pushing a flurry of updates for some of the build pipelines. I'll get to a new release in a day or two.

**Comment by Waffull** [comment]
Thanks for the armhf build.  I'm ended up rebuilding my amd64 device...  but it's something I'll probably use to learn about docker where I have an RPi slated for unifi-poller .  As soon as the amd64 system is finished being imaged...  I'll give the manual process another go and see if I can't figure out what I was doing wrong.

**Comment by davidnewhall** [comment]
Go is usually pretty easy, especially on a fresh system. You can cross compile arm from an amd64 system. Are you using some flavor of Debian? I operate mostly on Ubuntu 16.04 and macOS 10.13 myself. I do all my testing and initial builds on a mac then send it to travis CI (on a debian instance) to make all the release packages that get uploaded to github. If you look at the .travis.yml file you get a small idea what is needed to get up and going. 

All that said, try this. This article looks like a good start https://tecadmin.net/install-go-on-debian/ - I just recommend setting GOPATH to the default of `~/go` instead of whatever that article is trying to tell us. Also get latest go version; 1.12.6 IIRC. Then:
```shell
# build utilities (redhat has a similar package group)
sudo apt install build-essential

# get dep
curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

mkdir -p $GOPATH/src/github.com/davidnewhall
cd $GOPATH/src/github.com/davidnewhall
git clone https://github.com/davidnewhall/unifi-poller.git
cd unifi-poller
dep ensure
make build
```
If `make build` fails, try running the command it prints out manually. Something like: 
```
go build -o unifi-poller -ldflags "-w -s -X github.com/davidnewhall/unifi-poller/unifipoller.Version=dev"
```

**Comment by Waffull** [comment]
Thanks for all the great info. I'm going to get to playing after my morning meetings (aka: time to play boss, lol.)

**Comment by davidnewhall** [comment]
Hit me up if I can help more! Discord works well too.
