### ISSUE TITLE
After firmware upgrade, restarts required

### ISSUE THREAD

**Issue by Waffull** [davidnewhall/unifi-poller#78]
Here are the log files.  I have to restart Grafana and Unifi-Poller after upgrading to firmware 4.0.49.

The last few lines of the file ..._2 show the time frame of the problem.  Data was simply not showing up before the restarts.
[my_file_poller_dataz.txt](https://github.com/davidnewhall/unifi-poller/files/3380132/my_file_poller_dataz.txt)
[my_file_poller_dataz_2.txt](https://github.com/davidnewhall/unifi-poller/files/3380133/my_file_poller_dataz_2.txt)

After restart, everything was back to working properly.

**Comment by davidnewhall** [comment]
Okay, so unifi-poller died when the controller become unavailable. That's actually intended and normal behavior. Past versions of the poller would just keep running, unable to collect any data. In this case, it looks like you need something to restart the docker container when it dies. I'm a docker noob, but it looks like you can achieve this by adding `--restart always` to your `docker run` (or `start`?) command. When using a package on Linux, `systemd` will automatically restart the poller. This line basically says the controller turned off (or restarted or.. something), and this made the poller stop:
```
Get https://192.168.95.4:8443/api/stat/sites: dial tcp 192.168.95.4:8443: connect: connection refused
```
When this happens the authentication cookie unifi-poller uses stops working. The controller can come back up, but the cookie is now invalid and a new one needs to be made. Re-making the cookie just means you need to start the poller back up.  I think setting up docker to auto restart is your fix here.

Refs
===

https://stackoverflow.com/questions/26852321/docker-add-a-restart-policy-to-a-container-that-was-already-created

https://docs.docker.com/engine/reference/run/#restart-policies---restart

**Comment by Waffull** [comment]
I'm not using docker.  Could never get it to work and haven't had time to
get back to it yet.  Have company coming this weekend, so it won't be until
next week sometime.

M

**Comment by davidnewhall** [comment]
hah then my advice was useless! What command do you type in to restart unifi-poller?
Can you show me the output of 
```shell
cat /lib/systemd/system/unifi-poller.service
sudo systemctl status unifi-poller
```

**Comment by Waffull** [comment]
To restart I use:
> sudo systemctl restart unifi-poller

> pi@UnifiStats:~ $ **cat /lib/systemd/system/unifi-poller.service**
# Sytemd service unit for unifi-poller.

[Unit]
Description=UniFi Poller - Stores UniFi Metrics in InfluxDB
After=network.target
Requires=network.target

[Service]
ExecStart=/usr/bin/unifi-poller $DAEMON_OPTS
EnvironmentFile=-/etc/default/unifi-poller
EnvironmentFile=-/etc/sysconfig/unifi-poller
Restart=on-error
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=unifi-poller
Type=simple
User=nobody

[Install]
WantedBy=multi-user.target
pi@UnifiStats:~ $ **sudo systemctl status unifi-poller**
● unifi-poller.service - UniFi Poller - Stores UniFi Metrics in InfluxDB
   Loaded: loaded (/lib/systemd/system/unifi-poller.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-07-10 13:01:58 EDT; 11h ago
 Main PID: 493 (unifi-poller)
    Tasks: 9 (limit: 2200)
   Memory: 14.0M
   CGroup: /system.slice/unifi-poller.service
           └─493 /usr/bin/unifi-poller

Jul 11 00:52:10 UnifiStats unifi-poller[493]: 2019/07/11 00:52:10 [INFO] UniFi Measurements Recorded. Sites: 2, Clients: 24, Wireless APs: 4
Jul 11 00:52:40 UnifiStats unifi-poller[493]: 2019/07/11 00:52:40 [INFO] UniFi Measurements Recorded. Sites: 2, Clients: 24, Wireless APs: 4
Jul 11 00:53:10 UnifiStats unifi-poller[493]: 2019/07/11 00:53:10 [INFO] UniFi Measurements Recorded. Sites: 2, Clients: 24, Wireless APs: 4
Jul 11 00:53:40 UnifiStats unifi-poller[493]: 2019/07/11 00:53:40 [INFO] UniFi Measurements Recorded. Sites: 2, Clients: 24, Wireless APs: 4
Jul 11 00:54:10 UnifiStats unifi-poller[493]: 2019/07/11 00:54:10 [INFO] UniFi Measurements Recorded. Sites: 2, Clients: 24, Wireless APs: 4
Jul 11 00:54:40 UnifiStats unifi-poller[493]: 2019/07/11 00:54:40 [INFO] UniFi Measurements Recorded. Sites: 2, Clients: 24, Wireless APs: 4
Jul 11 00:55:09 UnifiStats unifi-poller[493]: 2019/07/11 00:55:09 [INFO] UniFi Measurements Recorded. Sites: 2, Clients: 24, Wireless APs: 4
Jul 11 00:55:40 UnifiStats unifi-poller[493]: 2019/07/11 00:55:40 [INFO] UniFi Measurements Recorded. Sites: 2, Clients: 24, Wireless APs: 4
Jul 11 00:56:09 UnifiStats unifi-poller[493]: 2019/07/11 00:56:09 [INFO] UniFi Measurements Recorded. Sites: 2, Clients: 24, Wireless APs: 4
Jul 11 00:56:40 UnifiStats unifi-poller[493]: 2019/07/11 00:56:40 [INFO] UniFi Measurements Recorded. Sites: 2, Clients: 24, Wireless APs: 4
lines 1-19/19 (END)

**Comment by davidnewhall** [comment]
Sweet. Try killing it. `sudo pkill -9 unifi-poller` Does system restart it? Run `sudo systemctl status unifi-poller` again and see what it says about the process dying.

That `Restart=on-error` line should keep it running when it dies. if system does does not restart it, edit `/lib/systemd/system/unifi-poller.service` and change  `Restart=on-error` to `Restart=always` then run `sudo systemctl daemon-reload`. Then try kill unifi-poller again to see if systemd restarts it. Please report back.

**Comment by davidnewhall** [comment]
Grab the latest release. This bug is fixed. https://github.com/davidnewhall/unifi-poller/releases/tag/v1.5.0
