### ISSUE TITLE
make don't work (ronn not installed), app doesn't run using systemd

### ISSUE THREAD

**Issue by eckhardt83** [davidnewhall/unifi-poller#8]
~/unifi-poller$ make
for p in `find ./cmd -mindepth 1 -maxdepth 1 -type d`; do rm -f `echo ${p}|cut -d/ -f3`{,.1,.1.gz}; done
script/build_manpages.sh ./
Creating Man Page: cmd/unifi-poller/README.md -> ./unifi-poller.1.gz
script/build_manpages.sh: line 11: ronn: command not found
for p in `find ./cmd -mindepth 1 -maxdepth 1 -type d`; do go build -ldflags "-w -s" ${p}; done
/bin/sh: 1: go: not found
Makefile:10: recipe for target 'build' failed
make: *** [build] Error 127

**Comment by davidnewhall** [comment]
Install `ronn`. Some equivalent of `gem install ronn` for your environment will get you there. The other option is to edit the `Makefile` and change the line that says `install: man` to `install:` (without `man`) The step that is failing the building of a man (manual) page that is not entirely needed, but certainly helpful.

**Comment by davidnewhall** [comment]
Interesting. Have you ever built a go app previously? It seems like your build environment may not be setup properly. It looks like you have `$GOPATH` set to `~/work` so try this:
```
mkdir -p ~/work/src/github.com/davidnewhall
mv ~/unifi-poller ~/work/src/github.com/davidnewhall
cd ~/work/src/github.com/davidnewhall
make deps
make
```

Section 3 on this page may help explain: https://github.com/alco/gostart - this article is a good read for Go newcomers in general.

**Comment by cahpunke** [comment]
and now cant starup at debian 9. with systemd

**Comment by davidnewhall** [comment]
I'll admit I never tested any of this on Linux, only macOS. I hope I made that clear in the few docs I wrote. Please make sure the unit file is accurate for your environment and reload systemctl to pick  up any changes. I can help further, but I don't have a linux server to test on, and I'll need all the output/errors you have to further diagnose.

**Comment by davidnewhall** [comment]
Does the application start and run if you execute it manually? See here:
https://github.com/davidnewhall/unifi-poller/wiki/Installation

**Comment by davidnewhall** [comment]
Please let me know if I can assist further.

**Comment by davidnewhall** [comment]
There was a typo in the unit file for systemd. It was fixed here https://github.com/davidnewhall/unifi-poller/commit/13e284852d29376ab349c9487630b9f786b2396f - this likely caused your issue.

**Comment by davidnewhall** [comment]
I've released a number of new features and bug fixes. There are now binary packages (deb/rpm) available to make install a lot easier. Find those on the [Releases](https://github.com/davidnewhall/unifi-poller/releases) page if you're interested!

If you want to install using the Makefile, follow the [Installation](https://github.com/davidnewhall/unifi-poller/wiki/Installation) wiki.
