### ISSUE TITLE
Tiny issue: laid instead of Load in grafana graphs

### ISSUE THREAD

**Issue by rssfed23** [davidnewhall/unifi-poller#81]
An insignificant thing: in some of the grafana graphs it says Laid instead of Load (e.g UAP Insights > UAP Load Average > 5 minute load averages say laid).

But I'm also logging this as I wanted to say thanks for all the hard work the recent rate of improvements has been insane (especially the API changes in 5.11) and you deserve some kudos for that!!

**Comment by davidnewhall** [comment]
haha, I don't have a spell checker for Grafana. :D Need to figure that one out I suppose. 

I appreciate the praise, thank you very much! I'll be sure to look through all the graphs for typos before I release new revisions.

**Comment by davidnewhall** [comment]
I only found this particular typo in the one place you pointed out. It's fixed on my local version now. When I cut a new rev it'll be fixed there too. Thanks again!
