### ISSUE TITLE
Failed with result 'exit-code' invalid memory address

### ISSUE THREAD

**Issue by rottison** [davidnewhall/unifi-poller#87]
2019/07/16 21:37:03 [INFO] Everyt                                                                                                                                                           hing checks out! Poller started, interval: 30s
 controller unifi-poller[3575]: panic: runtime error: invalid memory address or nil pointer dereference
 controller unifi-poller[3575]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x22ea64]
 controller unifi-poller[3575]: goroutine 1 [running]:
 controller unifi-poller[3575]: github.com/davidnewhall/unifi-poller/vendor/github.com/golift/unifi.UAP.PointsAt(0x16e4b80, 0x18, 0x1, 0x16e190c, 0x4, 0x15d17a0, 0x1, 0x4, 0x16e1940, 0x9, ...)
Jul 16 21:37:33 controller unifi-poller[3575]: #011/home/travis/gopath/src/github.com/davidnewhall/unifi-poller/vendor/github.com/golift/unifi/uap_influx.go:22 +0x11c
Jul 16 21:37:33 controller unifi-poller[3575]: github.com/davidnewhall/unifi-poller/vendor/github.com/golift/unifi.UAP.Points(0x16e4b80, 0x18, 0x1, 0x16e190c, 0x4, 0x15d17a0, 0x1, 0x4, 0x16e1940, 0x9, ...)
Jul 16 21:37:33 controller unifi-poller[3575]: #011/home/travis/gopath/src/github.com/davidnewhall/unifi-poller/vendor/github.com/golift/unifi/uap_influx.go:12 +0x60
Jul 16 21:37:33 controller unifi-poller[3575]: github.com/davidnewhall/unifi-poller/unifipoller.(*Metrics).processPoints(0x159e090, 0x3deab0, 0x17f2000, 0x17f2000, 0x0)
Jul 16 21:37:33 controller unifi-poller[3575]: #011/home/travis/gopath/src/github.com/davidnewhall/unifi-poller/unifipoller/unifi.go:191 +0x2c
Jul 16 21:37:33 controller unifi-poller[3575]: github.com/davidnewhall/unifi-poller/unifipoller.(*Metrics).ProcessPoints(0x159e090, 0x173dcd8, 0x4, 0x173dcdc)
Jul 16 21:37:33 controller unifi-poller[3575]: #011/home/travis/gopath/src/github.com/davidnewhall/unifi-poller/unifipoller/unifi.go:175 +0x3f4
Jul 16 21:37:33 controller unifi-poller[3575]: github.com/davidnewhall/unifi-poller/unifipoller.(*UnifiPoller).ReportMetrics(0x146a240, 0x159e090, 0x0, 0x0)
Jul 16 21:37:33 controller unifi-poller[3575]: #011/home/travis/gopath/src/github.com/davidnewhall/unifi-poller/unifipoller/unifi.go:129 +0x20
Jul 16 21:37:33 controller unifi-poller[3575]: github.com/davidnewhall/unifi-poller/unifipoller.(*UnifiPoller).CollectAndReport(0x146a240, 0x15e5f14, 0x14fc101)
Jul 16 21:37:33 controller unifi-poller[3575]: #011/home/travis/gopath/src/github.com/davidnewhall/unifi-poller/unifipoller/unifi.go:73 +0x70
Jul 16 21:37:33 controller unifi-poller[3575]: github.com/davidnewhall/unifi-poller/unifipoller.(*UnifiPoller).PollController(0x146a240, 0x6, 0x14125f0)
Jul 16 21:37:33 controller unifi-poller[3575]: #011/home/travis/gopath/src/github.com/davidnewhall/unifi-poller/unifipoller/unifi.go:52 +0x130
Jul 16 21:37:33 controller unifi-poller[3575]: github.com/davidnewhall/unifi-poller/unifipoller.(*UnifiPoller).Run(0x146a240, 0x0, 0x0)
Jul 16 21:37:33 controller unifi-poller[3575]: #011/home/travis/gopath/src/github.com/davidnewhall/unifi-poller/unifipoller/start.go:101 +0x164
Jul 16 21:37:33 controller unifi-poller[3575]: github.com/davidnewhall/unifi-poller/unifipoller.Start(0x3e34c, 0x1442070)
Jul 16 21:37:33 controller unifi-poller[3575]: #011/home/travis/gopath/src/github.com/davidnewhall/unifi-poller/unifipoller/start.go:33 +0xf0
Jul 16 21:37:33 controller unifi-poller[3575]: main.main()
Jul 16 21:37:33 controller unifi-poller[3575]: #011/home/travis/gopath/src/github.com/davidnewhall/unifi-poller/main.go:11 +0x14
Jul 16 21:37:33 controller systemd[1]: unifi-poller.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 16 21:37:33 controller systemd[1]: unifi-poller.service: Unit entered failed state.
Jul 16 21:37:33 controller systemd[1]: unifi-poller.service: Failed with result 'exit-code'.
Jul 16 21:37:33 controller systemd[1]: unifi-poller.service: Service hold-off time over, scheduling restart.
Jul 16 21:37:33 controller systemd[1]: Stopped unifi-poller - Polls a UniFi controller and stores metrics in InfluxDB.

**Comment by rottison** [comment]
I have deleted the unifi-poller script and reinstalled the newest version with the curl line from the install page. I have also deleted the database and reinstalled. And re-downloaded the grafana dashboards trying to get back to a fresh start I also checked the variables and they are there.
Thanks for reading

**Comment by davidnewhall** [comment]
This is fixed in the `latest` docker build, but I have not cut a new release yet with the patch (no packages). If you can compile it yourself, you can create a package with the fix. I'll make a new release tonight or tomorrow that you can use. This happens because of disable devices. If you remove the disabled device from the site being polled this will also stop happening.

**Comment by rottison** [comment]
ok I can readd the AP i took off line
not sure I can compile it myself

**Comment by rottison** [comment]
David thanks for the tip I plugged in the AP and all is working again I have been working on that for almost 2 hours

**Comment by davidnewhall** [comment]
Sorry about that! This was reported a couple days ago. The reporter was able to figure out it was a disabled device causing the crash. I've since committed a fix; just need to make a new release... been working on some other projects.

**Comment by davidnewhall** [comment]
The current release (1.5.1) solves this issue. Please upgrade!
