### ISSUE TITLE
UniFi Controller logs out Poller after 30 second interval

### ISSUE THREAD

**Issue by Kasperdebruin** [davidnewhall/unifi-poller#89]
Hi,

Im getting the error no datapoint, i configured everything as said in the tutorial. Any thoughts how to solve this problem?
It says: my data source is working.
![image](https://user-images.githubusercontent.com/53341012/62033723-dbd3cd80-b1ec-11e9-8949-2113d88d8035.png)

![image](https://user-images.githubusercontent.com/53341012/62033821-22292c80-b1ed-11e9-9853-3b537c2731e9.png)

Thanks in advance!
With kind regards,
Kasper de Bruin

**Comment by davidnewhall** [comment]
This is likely due to the variables in the dashboards having the wrong data source. In each dashboard, click the settings gear icon, then click Variables, then click on one of the variables. Make sure the data source is correct (unifi or whatever you named it). Sometimes this happens. 

Other possible causes: 
- missing grafana plugins
- old grafana (recommended 6.2+)

**Comment by Kasperdebruin** [comment]
![image](https://user-images.githubusercontent.com/53341012/62034552-826c9e00-b1ee-11e9-91ce-03f15301855f.png)

**Comment by davidnewhall** [comment]
_The preview of values is shown as empty._ That's telling me there's no data coming up for sites.. Does the poller output show data being collected?

**Comment by davidnewhall** [comment]
The `Data Source` says `InfluxDB` - Do you have other options? Like `unifi`?

**Comment by Kasperdebruin** [comment]
> The `Data Source` says `InfluxDB` - Do you have other options? Like `unifi`?

Yes only -grafana, but I named the influxdb datasource InfluxDB/

**Comment by Kasperdebruin** [comment]
> _The preview of values is shown as empty._ That's telling me there's no data coming up for sites.. Does the poller output show data being collected?

How to check this?

**Comment by davidnewhall** [comment]
There's a lot of good troubleshooting in this thread. https://github.com/davidnewhall/unifi-poller/issues/77

**Comment by davidnewhall** [comment]
Log into the influxdb and check for data. Try changing the graphs to see if the data is there. Examples in #77.

**Comment by davidnewhall** [comment]
I'll be back after a while. Time for bed. Let me know what you figure out!

**Comment by Kasperdebruin** [comment]
![image](https://user-images.githubusercontent.com/53341012/62047458-d5ece500-b20a-11e9-8826-b7299c3ca77b.png)

**Comment by Kasperdebruin** [comment]
When i use the command sudo _grep unifi-poller /var/log/syslog /var/log/messages | tail -n 1000 | tee my_file_poller_dataz.txt_ it shows me this:
**/var/log/syslog:Jul 29 13:17:18 ubugra01 unifi-poller[8647]: 2019/07/29 13:17:18 [INFO] Loading Configuration File: /etc/unifi-poller/up.conf
/var/log/syslog:Jul 29 13:17:18 ubugra01 unifi-poller[8647]: 2019/07/29 13:17:18 [INFO] UniFi Poller v1.5.1-364 Starting Up! PID: 8647
/var/log/syslog:Jul 29 13:17:18 ubugra01 systemd[1]: Started unifi-poller - Polls a UniFi controller and stores metrics in InfluxDB.
/var/log/syslog:Jul 29 13:17:18 ubugra01 unifi-poller[8647]: 2019/07/29 13:17:18 [INFO] Authenticated to UniFi Controller at _https://unifisite....._ version 5.10.25 as user influxdb**

It looks good to me.

**Comment by davidnewhall** [comment]
The screenshot you pasted is missing the graph. Did it work?

The logs are cut off before it gets to the application output's repeating output. Does it tell you every 30 seconds that it collected data? Are there any errors?

**Comment by Kasperdebruin** [comment]
The graph didn't work, it still says no data points. No I'm not getting any errors.

**Comment by davidnewhall** [comment]
If you make a simple UAP CPU graph like one in #77, are you able to get data?

![](https://user-images.githubusercontent.com/2402929/61000474-5b6b2c80-a312-11e9-9038-5686d1251ae8.png)

Can we chat on Discord?

**Comment by Kasperdebruin** [comment]
![image](https://user-images.githubusercontent.com/53341012/62133030-6d6f3800-b2de-11e9-9603-ae6ae67fa5bb.png)
still getting no data points... It's also not auto populating the fields.

**Comment by Kasperdebruin** [comment]
and ofcourse my username is kaspoehh id 9931

**Comment by davidnewhall** [comment]
Is there data in InfluxDB?

**Comment by Kasperdebruin** [comment]
how can i see that?

**Comment by davidnewhall** [comment]
```
$ influx
Connected to http://localhost:8086 version v1.7.7
InfluxDB shell version: v1.7.7
> use unifi
Using database unifi
> select * from uap limit 1;
```

**Comment by Kasperdebruin** [comment]
Nope I'm not getting any data.

**Comment by davidnewhall** [comment]
Can you paste 10 or so log lines that come after this one? 
```
Authenticated to UniFi Controller at https://link to unifi controller..... version 5.10.25 as user influxdb
```
 I'm on Discord now too if you want to chat there.

**Comment by davidnewhall** [comment]
If anyone has any ideas....
The problem here seems to be that the controller quickly times out the authentication cookie. We have been unable to determine why. The first couple requests when the poller starts are okay, but after 30 seconds the poller is logged out, and all requests fail.
