### ISSUE TITLE
Unmarshalling Device Type: uap

### ISSUE THREAD

**Issue by cahpunke** [davidnewhall/unifi-poller#9]
im use go1.9 debian 9 

2019/01/22 11:06:01.345408 main.go:45: Authenticated to Unifi Controller @ https://127.0.0.1:8443 as user influxdb
2019/01/22 11:06:01.345507 main.go:55: Logging Unifi Metrics to InfluXDB @ http://127.0.0.1:8086 as user noc
2019/01/22 11:06:01.345527 main.go:56: Polling Unifi Controller, interval: 30s
2019/01/22 11:06:31.563911 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.566287 unifi.go:111: Unmarshalling Device Type: ugw
2019/01/22 11:06:31.568523 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.571180 unifi.go:111: Unmarshalling Device Type: usw
2019/01/22 11:06:31.574514 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.577082 unifi.go:111: Unmarshalling Device Type: usw
2019/01/22 11:06:31.579343 unifi.go:111: Unmarshalling Device Type: usw
2019/01/22 11:06:31.582041 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.585247 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.587078 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.587194 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.589279 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.592460 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.595709 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.598269 unifi.go:111: Unmarshalling Device Type: usw
2019/01/22 11:06:31.601013 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.603322 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.605519 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.607328 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.608812 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.610634 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.612807 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.616031 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.619283 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.622464 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.625608 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.628774 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.631954 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.635669 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.639346 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.642014 unifi.go:111: Unmarshalling Device Type: usw
2019/01/22 11:06:31.643603 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.643682 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.643759 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.643831 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:31.643901 unifi.go:111: Unmarshalling Device Type: uap
2019/01/22 11:06:38.511510 main.go:116: Logged client state. Clients: 270 - Devices: 36

**Comment by davidnewhall** [comment]
You have a tone of WAPs. My goodness. This looks like it's working. Have you setup the graphs yet?

**Comment by cahpunke** [comment]
unifi-clients-grafana-dash graphic templates do not appear/ blank while templates for UAP appear.

**Comment by davidnewhall** [comment]
You may need to do some spelunking in Influx and Grafana to see if the data is there or not. Maybe something about the graph doesn't work in your environment. The message you pasted in your original post is "good" output. It got all the devices and turned their data structures into Go types without errors. The unmarshalling process is typical where things go bad. In your case, it all looks good. 

Try to make some new graphs and see if the data is in Infolux...

**Comment by davidnewhall** [comment]
Does the application start and run if you execute it manually? See here:
https://github.com/davidnewhall/unifi-poller/wiki/Installation

**Comment by davidnewhall** [comment]
Were you able to get your graphs working? I'm curious how things are working out. You have a lot of devices and I'm curious if things are working ok or not..

**Comment by davidnewhall** [comment]
Please let me know if I can provide additional assistance to get this working in your environment.

**Comment by davidnewhall** [comment]
I think this is because some of Grafana plugins were not installed.
