### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by DB-Vincent** [davidnewhall/unifi-poller#90]
For the past couple of hours I've been trying to get Unifi-Poller to work on my debian machine, but without success. I don't get past the start. This is what I see when checking the logs:
![Capture](https://user-images.githubusercontent.com/48948316/62036634-71be2700-b1f2-11e9-97cb-f01db37f6948.PNG)

I've put my info in the configuration file and all seems to be correct.

**Comment by davidnewhall** [comment]
Check the output of the poller logs. What you've pasted looks like journal entries from systemd. Try `sudo systemctl status unifi-poller` and/or `grep unifi-poller /var/log/{messages,syslog}`

**Comment by davidnewhall** [comment]
My guess is the poller is having troubles connecting to either the controller or to influxdb. The output should show you what's wrong. If you can't find the logs, you can always try running it manually: `unifi-poller -D` or `unifi-poller -D -c /path/to/up.conf`

**Comment by DB-Vincent** [comment]
For some weird reason neither `sudo systemctl status unifi-poller` or `grep unifi-poller /var/log/{messages,syslog}` returned anything useful (grep returned what I showed in the screenshot). When just executing `unifi-poller` it started up and got working. 

Thanks!

**Comment by davidnewhall** [comment]
This sounds like a problem with the service unit file. hm...

Can you show me what's in this file? `cat /lib/system/systemd/unifi-poller.service` Is `unifi-poller` in the correct location? Should be `/usr/bin/unifi-poller`. Does `/etc/default/unifi-poller` exist? What's in it if it does?

**Comment by davidnewhall** [comment]
Did you install the deb package? version 1.5.1? Maybe try uninstalling and reinstalling. Kinda throwing rocks here.

**Comment by DB-Vincent** [comment]
The unifi-poller.service file has the following contents:
`vincent@vdbdeb002:/lib/systemd/system$ cat unifi-poller.service
# Systemd service unit for unifi-poller.
# This is part of Application Builder.
# https://github.com/golift/application-builder

[Unit]
Description=unifi-poller - Polls a UniFi controller and stores metrics in InfluxDB
After=network.target
Requires=network.target

[Service]
ExecStart=/usr/bin/unifi-poller $DAEMON_OPTS
EnvironmentFile=-/etc/default/unifi-poller
EnvironmentFile=-/etc/sysconfig/unifi-poller
Restart=always
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=unifi-poller
Type=simple
User=nobody

[Install]
WantedBy=multi-user.target
`
_unifi-poller_ is in the correct location and `/etc/default/unifi-poller` does not exist.

**Comment by davidnewhall** [comment]
Seems very strange. The error 127 you're getting from systemd indicates that the unifi-poller binary is not found, or not executable. I wonder..... Did you install an old version of unifi-poller a long time ago maybe?
Do you have this file on your system: `/etc/system/systemd/unifi-poller.service` ?

**Comment by DB-Vincent** [comment]
No, but I have that file located at 
`/lib/systemd/system/unifi-poller.service`, the contents of that file are in my previous comment.

**Comment by davidnewhall** [comment]
Gotcha. Older installs put it in the /etc/ path, and if you have both, /etc always wins.

I'm not entirely sure why systemd is having a problem with that service, or why it's hiding the logs from you. If you want to jump into Discord, maybe we can do a screen share and poke around a bit together. Let me know.

**Comment by DB-Vincent** [comment]
Sure, my Discord username is Jumperlow#3599.

**Comment by davidnewhall** [comment]
Come say hi https://discord.gg/DyVsMyt

**Comment by davidnewhall** [comment]
We worked this out in Discord.
