### ISSUE TITLE
Unifi connection timed out

### ISSUE THREAD

**Issue by meelime** [davidnewhall/unifi-poller#92]
Hi,
I followed instructions to install Unifi-poller without any problem, but when I go in Grafana, I don't have any data. I looked at the logs and I have this:

`[ERROR] unifi controller: authReq.Do(req): Post https://server:8443/api/login: dial tcp ipserver:8443: connect: connection timed out`

Not sure what I have to do.

Thank you very much! :)

**Comment by davidnewhall** [comment]
It's saying it can't connect to `https://server:8443`.
Can you `curl` it from the same server?

**Comment by meelime** [comment]
Sorry, my bad. I was sure there wasn't a rule in the firewall, but apparently there was and it blocked port 8443!

now it works :) thank you!

**Comment by davidnewhall** [comment]
Great to hear!! If you like the dashboards, please leave a five star review on Grafana 💯It helps others find this applications. Thanks!
