### ISSUE TITLE
re-start of unifi poller

### ISSUE THREAD

**Issue by rottison** [davidnewhall/unifi-poller#93]
I run my controller on a pi 3+ and influx and grafana are dockers on my unraid machine I had problems with my pi after a storm rolled threw and one time when I had to manually hard boot the pi both times after restarting the pi there was no data going in to the graphs I had to restart the poller and all started to look good again this is not a problem just more if you stop seeing data going in tot he graphs try restarting the poller and see if it helps before you start done a rabbit hole

**Comment by davidnewhall** [comment]
it kinda sounds like the Docker containers are starting out of order. I could add a start delay to the poller, or something to make it wait a minute after starting up before trying to connect to the controller or influx. I've noticed the controller can sometimes take 30s to start, and if the poller starts it will quickly exit when the controller is not available. 

In your situation, was the unifi-poller docker container still running? If yes, what were the logs saying? If it was stopped, can you set it to auto re-start? That should help.

**Comment by rottison** [comment]
I have the poller running on the pi with the controller then the dockers are running on a different machine the dockers never stopped only the pi with poller and the controller need to have an auto start for the controller

**Comment by davidnewhall** [comment]
Oh you're using a package install for the poller, not the docker image? Systemd should keep the poller running if it stops.

**Comment by rottison** [comment]
yup was thinking that also

**Comment by davidnewhall** [comment]
Can you share logs from the event, so we can try to figure out why that didn't happen?

**Comment by davidnewhall** [comment]
Hit me up on Discord if this happens again; let's dig through it! Thanks!. :)
