### ISSUE TITLE
Controller Authentication Error

### ISSUE THREAD

**Issue by bbengt1** [davidnewhall/unifi-poller#94]
Hello when running the docker image I am getting this error.

[ERROR] unifi controller: authentication failed (user: influxdb): https://xx.xx.xx.xx:8443/api/login (status: 400 )

Controller firmware version v1.0.9

I did make my own image from your instructions "make docker" as I did do some customer env variables in the config.go file before making image. Anything I might be missing here?

---
On a side note have you ever seen someone successfully deploy this on a Kubernetes Cluster? 

I am working on getting this customized image up and running on docker first and then moving it over to a Kubernetes cluster.

**Comment by davidnewhall** [comment]
> Anything I might be missing here?

The changes you made aren't here. Did it work before you made changes? Did you add a user named `influxdb` to your controller? Can you login to the controller as that user?

> Have you ever seen someone successfully deploy this on a Kubernetes Cluster?

I have not, but people don't tend to report success with the app. It's possible someone has, I just haven't heard about it.

**Comment by bbengt1** [comment]
I built a new image locally on my laptop and trying to run it in docker desktop. Thinking this is definitely an issue on my end here on the way I am trying to run it. Going on vacation for a week so I won't have much time to dig into this further till I get back. I am going to close it for now. 

Thanks for the info on Kubernetes, my plan is to try and get this up and running there at some point so if I have some luck I will let you know.

**Comment by davidnewhall** [comment]
Sounds good! You can always fork the repo, and push your changes into your local copy. Then I can take a look at what's moving around (and maybe add your changes to an official release).

Looking forward to your update. Good luck!

**Comment by davidnewhall** [comment]
Curious if the current Docker image solves this now days.
