### ISSUE TITLE
reporting metrics: influxdb.Write(points): 405: Method Not Allowed

### ISSUE THREAD

**Issue by THland83** [davidnewhall/unifi-poller#95]
2019/08/13 23:33:44 [INFO] Loading Configuration File: C:\ProgramData\unifi-poller\up.conf
2019/08/13 23:33:44 [INFO] UniFi Poller v1.5.1-364 Starting Up! PID: 16520
2019/08/13 23:33:45 [INFO] Authenticated to UniFi Controller at https://192.168.1.12:8443 version 5.10.26 as user InfluxDB
2019/08/13 23:33:45 [INFO] Found 1 site(s) on controller: default (Default)
2019/08/13 23:33:45 [INFO] Polling UniFi Controller Sites: [all]
2019/08/13 23:33:45 [INFO] Logging Measurements to InfluxDB at http://192.168.1.12:8123/hassio/ingress/a0d7b954_influxdb as user unifi
2019/08/13 23:33:45 [INFO] Everything checks out! Poller started, interval: 30s
2019/08/13 23:34:15 [ERROR] (1/5) reporting metrics: influxdb.Write(points): 405: Method Not Allowed

**Comment by davidnewhall** [comment]
This sounds like a bad username and password for influxdb. Can you log in with the `influx` cli command using the name and password you've provided in `up.conf`?

**Comment by davidnewhall** [comment]
It looks like this (my influx doesn't require auth):
```
> unifi:~ admin$ influx -host 127.0.0.1 -port 8086 -database unifi
Connected to http://127.0.0.1:8086 version v1.7.7
InfluxDB shell version: v1.7.7
> select * from uap limit 1;
name: uap
time                adopted bandsteering_mode board_rev bytes       bytes_d  bytes_r cfgversion       config_network_ip config_network_type connect_request_ip connect_request_port considered_lost_at cpu default device_ap         device_id                device_oid        device_type discovered_via
<more data here>
```

**Comment by THland83** [comment]
No CLI for InfluxDB within Hassio

I think this is due to Homeassistant only accepting post commands?

https://www.home-assistant.io/components/http/#http-sensors
https://developers.home-assistant.io/docs/en/external_api_rest.html#post-apistatesltentity_id

**Comment by davidnewhall** [comment]
You can install the influx cli on any *nix system pretty easy. apt, yum, brew..

I'm afraid I'm not familiar with Home Assistant. The page you linked doesn't mention influxdb anywhere. Was that the correct link? I clicked through many of the navigation page links on the left -- searching for "influx" -- nothing shows up. Are you sure there's an InfluxDB in that software? One you can write to directly?

**Comment by davidnewhall** [comment]
This link may help get you going. https://www.home-assistant.io/components/influxdb/ - it has some links at the top with the resources to setup influxdb for use with home assistant.

**Comment by davidnewhall** [comment]
Were you able to get InfluxDB going?

**Comment by THland83** [comment]
Pardon the delayed response. Influx is definitely running, I'm receiving data from other sources, however those other sources are on the same machine. In this case, the data is being scraped by a windows machine and then pushed across in an HTTP protocol.

I believe it's related to a nuance in HASSIO that doesn't allow a "write" request to be sent over HTTP and then is rejecting it. 

In the docs I posted, it looks like the request needs to go across a specific API url, however a curl command is required to grab the auth header.

Im pretty thin on programing so don't take any of this as exact. I'm throwing my gut feeling out with this. 

Appreciate the responses, definitely an interesting project.

**Comment by davidnewhall** [comment]
This application only supports InfluxDB. You should give it an IP with port 8086 (which is HTTP) that goes to the InfluxDB instance you configured. I'm not sure how or why the hass API has anything to do with this. The docs I read pretty much said "InfluxDB is independent from Hassio: here's the public docs to install it." The page I linked clearly shows the correct default port for InfluxDB, but you're using the API port. The poller doesn't know how to use that API. Have you tried this?
```
influx_url = "http://192.168.1.12:8086"
influx_user = "unifi"
```

**Comment by THland83** [comment]
2019/08/15 13:20:03.041861 start.go:117: [INFO] Logging Measurements to InfluxDB at http://192.168.1.12:8086/a0d7b954_influxdb as user unifi
2019/08/15 13:20:03.041861 unifi.go:49: [INFO] Everything checks out! Poller started, interval: 30s
2019/08/15 13:20:33.053590 unifi.go:132: [DEBUG] Found 1 site(s): default
2019/08/15 13:20:33.053590 unifi.go:80: [DEBUG] Polling Controller, retreiving UniFi Clients, site default (Default)
2019/08/15 13:20:33.108444 devices.go:16: [DEBUG] Unmarshalling Device Type: uap, site Default (default)
2019/08/15 13:20:33.110438 devices.go:16: [DEBUG] Unmarshalling Device Type: uap, site Default (default)
2019/08/15 13:20:33.111436 devices.go:16: [DEBUG] Unmarshalling Device Type: uap, site Default (default)
2019/08/15 13:20:33.112433 devices.go:16: [DEBUG] Unmarshalling Device Type: ugw, site Default (default)
2019/08/15 13:20:33.113430 devices.go:16: [DEBUG] Unmarshalling Device Type: usw, site Default (default)
2019/08/15 13:20:33.114428 devices.go:16: [DEBUG] Unmarshalling Device Type: usw, site Default (default)
2019/08/15 13:20:33.118417 unifi.go:74: [ERROR] (1/0) reporting metrics: influxdb.Write(points): 404 page not found
2019/08/15 13:20:33.118417 main.go:12: [ERROR] reached maximum error count, stopping poller (1 > 0)

**Comment by davidnewhall** [comment]
Remove `a0d7b954_influxdb` from the path.

**Comment by THland83** [comment]
That was the ticket

2019/08/15 13:32:39.377515 unifi.go:80: [DEBUG] Polling Controller, retreiving UniFi Clients, site default (Default)
2019/08/15 13:32:39.399457 devices.go:16: [DEBUG] Unmarshalling Device Type: uap, site Default (default)
2019/08/15 13:32:39.400454 devices.go:16: [DEBUG] Unmarshalling Device Type: uap, site Default (default)
2019/08/15 13:32:39.401451 devices.go:16: [DEBUG] Unmarshalling Device Type: uap, site Default (default)
2019/08/15 13:32:39.401451 devices.go:16: [DEBUG] Unmarshalling Device Type: ugw, site Default (default)
2019/08/15 13:32:39.402449 devices.go:16: [DEBUG] Unmarshalling Device Type: usw, site Default (default)
2019/08/15 13:32:39.403446 devices.go:16: [DEBUG] Unmarshalling Device Type: usw, site Default (default)
2019/08/15 13:32:39.425387 unifi.go:146: [INFO] UniFi Measurements Recorded. Sites: 1, Clients: 24, Wireless APs: 3, Gateways: 1, Switches: 2, Points: 69, Fields: 3000

**Comment by davidnewhall** [comment]
Sweet!

**Comment by THland83** [comment]
Having addtional issues with Grafana now, but ill do some research before reaching out again

Site doesn't seem to populate, which is i think is causing "Cannot read property 'map' of undefined" across the panels

**Comment by davidnewhall** [comment]
Make sure you're running at least Grafana 5.5; 6.x is recommended. And don't forget to install the plugins. https://github.com/davidnewhall/unifi-poller/wiki/Grafana#plugins

**Comment by davidnewhall** [comment]
We wrapped this up in Discord. Was a data source typo. 

Good luck!!
