### ISSUE TITLE
"show tag values" not returning anything

### ISSUE THREAD

**Issue by apetrycki** [davidnewhall/unifi-poller#96]
I'm having the same/similar issue as #77.  It looks like it's using the correct database, so I tried the query (ex. show tag values from "clients" with key="site_name") with the influx cli and it returns nothing.  All my data is there and I can see it if I remove the variables from the queries in the dashboard.  What was the solution for #77?

**Comment by apetrycki** [comment]
Looks like it was a version issue with influxdb.  I had version 1.6.4 which is available in the main repo for raspberry pi buster.  After upgrading to 1.7.7, I get the correct response and everything is working.

```
sudo apt-get remove influxdb influxdb-client -y
wget -qO- https://repos.influxdata.com/influxdb.key | sudo apt-key add -
echo "deb https://repos.influxdata.com/debian buster stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
sudo apt-get update
sudo apt-get install influxdb
```

I'm not sure what version is needed, but you might want to include this info in the install.

**Comment by davidnewhall** [comment]
I'm glad you were able to figure this out. Thank you for updating and letting us know what resolved it for you! I'm also tickled that you did the data troubleshooting first, thanks! That really helps resolve these issues quickly.

I'm going to put together a troubleshooting wiki at some point, and this information will be included there. I'm unfortunately not sure what versions of InfluxDB work, I've only ever personally used the version that installed on my mac with Homebrew (1.7.7). I also see several open bugs with InfluxDB pertaining to missing data with `SHOW TAG VALUES` across versions from 1.5 to 1.7. That tells me it's entirely possible 1.6.x may work for some but not for others. 

I'll make a note that InfluxDB 1.7.x while 1.7.7 is well tested, and users have reported problems with 1.6.x. Please let me know if I can help with anything else!
