### ISSUE TITLE
Unifi Controller 5.11.38: [ERROR] json.Unmarshal(uap): Cannot unmarshal to FlexInt

### ISSUE THREAD

**Issue by ChristophGoth** [davidnewhall/unifi-poller#97]
With Controller 5.11.38 there comes a problem back again:

2019/08/15 12:46:10.277474 devices.go:47: [ERROR] json.Unmarshal(uap): Cannot unmarshal to FlexInt

UAP and Clients Dashboard only showing a few data.

I'm running in docker, release latest and stable tried without success.
Log is attached.
[log.txt](https://github.com/davidnewhall/unifi-poller/files/3505564/log.txt)

**Comment by davidnewhall** [comment]
Dang. This is the problem with beta software. They're always changing things. It seems they've changed a number to data structure. Thanks for the log! I'll scan through this payload and figure out what changed, and get it fixed by next week.

**Comment by davidnewhall** [comment]
This should be fixed in `latest` tag. Can you give it a try and let me know?

**Comment by ChristophGoth** [comment]
Looks good, just upgraded Docker and no error in logs visible. Client Stats got filled again, will watch it for some time. Thanks for the great work.
