### ISSUE TITLE
UDM as an asset type

### ISSUE THREAD

**Issue by ahiguero** [davidnewhall/unifi-poller#98]
great product. one thing that i am am noticing is that the UDM is an unknown asset type therefore it is skipped with the following message in the logs:

[ERROR] unknwon asset type  - udm  - skipping

can this be added?

**Comment by davidnewhall** [comment]
UDM is still early access? I don't know hardly anything about it. I do not have one to get the api output. But you do, and you can help me. :D 

Run `unifi-poller -j d` to print out the json payload. Pipe to jq to format it better. `| jq` - Put the UDM json portion (or all of it) into a gist.

The whole command to save the output might look like:
`unifi-poller -j d -c /path/to/up.conf | jq | tee controller.json`

**Comment by davidnewhall** [comment]
If you can provide this data, I can likely add support for the device. Thanks!

**Comment by Waffull** [comment]
I could get this info for you.... but my unifi-poller installation has
stopped working.. Getting "Network Error: Bad Gateway(502)" in Grafana and
influxd isn't running and won't start.  I already tried reinstalling it and
removing then installing.  Something giving me a major headache... Don't
understand since not only didn't I make any changes, I haven't done
anything but look at the Grafana dashboards for the past few weeks.

**Comment by davidnewhall** [comment]
Technically, you don't need influx or Grafana to dump the controller data. You only need the unifi-poller binary, up.conf and a network connection to your Unifi controller.

Grafana giving you a bad gateway message sounds just like what you described: influxdb is not running. 

Jump in discord and lets fix your Influx. ;)

**Comment by davidnewhall** [comment]
I was able to get a UDM Pro dump from vizir in the Ubiquiti Discord. I'll see if we can't make this work.

**Comment by ahiguero** [comment]
I am trying to get you the son dump but I am unfamiliar with the jq command

**Comment by davidnewhall** [comment]
You an skip `jq`. or install it: `sudo apt install -y jq  || sudo yum install jq`.

Without `jq`:
```
unifi-poller -j d -c /path/to/up.conf  | tee controller.json
```

All `jq` does is format the json. It's not needed.

**Comment by davidnewhall** [comment]
Someone else had problems with this earlier. This command should work.
```
unifi-poller -j d -c /path/to/up.conf > controller.json 2>&1
```

**Comment by Waffull** [comment]
What's your Discord? I'm MedicNYC on Discord.

Sorry for late reply, was away from computer all day.

Thanks,
Marc

**Comment by davidnewhall** [comment]
TwitchCaptain. The person that DM'd you a week ago and you never replied. ;)

**Comment by davidnewhall** [comment]
This should be fixed in `latest` / master branch. I'll cut a release soon.
